cmu-db/peloton

src/backend/bridge/dml/expr/expr_transformer.cpp, src/backend/bridge/dml/expr/pg_func_map.cpp, src/backend/common/value.h, src/backend/expression/expression_util.cpp, src/backend/expression/operator_expression.h
Implemented the mod operator and ran clang on all files.
=> Implemented mod operator

scripts/testing/dml/date.sql, src/backend/bridge/dml/expr/expr_transformer.cpp, src/backend/bridge/dml/expr/pg_func_map.cpp, src/backend/bridge/dml/tuple/tuple_transformer.cpp, src/backend/common/types.cpp, src/backend/common/types.h, src/backend/expression/Makefile.am, src/backend/expression/date_expression.h, src/backend/expression/date_functions.h, src/backend/expression/expression_util.cpp
formatted tuple_transformer.cpp and types.cpp.
=> Added basic extract operator

src/backend/bridge/Makefile.am, src/backend/bridge/dml/mapper/dml_utils.cpp, src/backend/bridge/dml/mapper/dml_utils.h, src/backend/bridge/dml/mapper/mapper.cpp, src/backend/bridge/dml/mapper/mapper.h, src/backend/bridge/dml/mapper/mapper_result.cpp
currently the returned ResultPlan is always set to NULL. will fix this problem later.
=> add support for ResultPlan. 

src/backend/networking/tcp_connection.cpp, src/postgres/backend/postmaster/postmaster.cpp
=> delete simple test code

src/backend/concurrency/optimistic_transaction_manager.cpp, src/backend/executor/delete_executor.cpp, src/backend/executor/insert_executor.cpp, src/backend/executor/update_executor.cpp
@MattPerron @eric-haibin-lin  you may directly edit optimistic_transaciton_manager.cpp.
=> update for the logging team

src/backend/common/lockfree_queue.h, src/backend/common/lockfree_spsc_queue.h
@amaliujia I have ported two lockfree queues to Peloton. I think they can meet your need in #124.
=> add lockfree queues

scripts/installation/Vagrantfile
=> Fixed incorrect URLs in Vagrantfile

src/backend/networking/Makefile.am
=> change Makefile to be aware of proto file changes

.travis.yml, src/backend/benchmark/tpcc/tpcc_workload.cpp, src/backend/storage/data_table.cpp
=> update travis to compile all log message #161

src/include/optimizer/abstract_optimizer.h, src/optimizer/abstract_optimizer.cpp, src/optimizer/rule_impls.cpp
In this simple PR we added a header and a source file for abstract_optimizer as we will start building on top of it.
=> Added abstract optimizer header and source file

src/concurrency/timestamp_ordering_transaction_manager.cpp, src/storage/data_table.cpp
minor change. jenkins failed because of the unused variable.
=> fix jenkins failure

src/catalog/catalog_util.cpp, src/common/types.cpp, src/concurrency/transaction_manager_util.cpp, src/executor/delete_executor.cpp, src/executor/index_scan_executor.cpp, src/executor/logical_tile.cpp, src/executor/update_executor.cpp, src/include/common/abstract_tuple.h, src/include/concurrency/transaction_manager_util.h, src/include/executor/logical_tile.h, src/include/expression/container_tuple.h, src/include/planner/project_info.h, src/include/storage/data_table.h, src/include/storage/tile_group.h, src/include/storage/tuple.h, src/planner/project_info.cpp, src/storage/data_table.cpp, src/storage/tile_group.cpp, src/storage/tuple.cpp
I need Ziqi's help for addressing the memory leak problem. We should reclaim memories allocated for `ItemPointer` pointer when deconstructing the index.
=> merge with master branch

.travis.yml, CMakeLists.txt, README.md, cmake/Modules/Coveralls.cmake, test/CMakeLists.txt
#212 
1. Fix the coveralls test by adjusting the setting of CXX flags.
2. Enable coveralls test in travis ci.
=> Enable the coverage test

cmake/Dependencies.cmake, src/CMakeLists.txt, src/common/allocator.cpp
=> fix jemalloc link issue

script/testing/jdbc/src/PelotonTest.java, src/common/numeric_value.cpp, src/executor/seq_scan_executor.cpp, src/include/planner/abstract_scan_plan.h, src/include/planner/index_scan_plan.h, src/optimizer/simple_optimizer.cpp, src/planner/index_scan_plan.cpp, src/planner/seq_scan_plan.cpp
This PR contains
- Support for "FOR UPDATE" in Planners
=> "For Update" Flag In planner

.travis.yml, src/executor/logical_tile.cpp, src/include/common/logger.h, src/include/storage/tuple.h, test/executor/executor_tests_util.cpp
The PR fixed the broken debugging information macros of the system.
=> Fix the debug logger

.travis.yml, script/testing/jdbc/src/PelotonTest.java
=> Modified jdbc validator path in travis

src/executor/hybrid_scan_executor.cpp, src/executor/seq_scan_executor.cpp, src/include/expression/expression_util.h, src/include/index/scan_optimizer.h, src/optimizer/simple_optimizer.cpp
#236
Fix the LOG_LEVEL_TRACE. Now we can compile with "-DLOG_LEVEL=LOG_LEVEL_TRACE".
=> Fix LOG_LEVEL_TRACE

src/wire/socket_base.cpp
=> fix for hanging when a buffer only partially writes to the socket

src/common/varlen_value.cpp, src/include/parser/statement_create.h
=> Create Table with FLOAT and DECIMAL types (now it's an alias for double)

src/include/common/value_factory.h, src/optimizer/simple_optimizer.cpp, src/planner/index_scan_plan.cpp
=> Takes care of some issues with prepared statements

src/common/value.cpp, src/executor/aggregate_executor.cpp, src/include/common/value_factory.h, src/include/storage/tuple.h, src/optimizer/simple_optimizer.cpp, src/storage/tuple.cpp, test/index/index_util_test.cpp
This fixes the retrying of StockLevel [#279]. The main issue is that we should return 0 instead of null when there's no tuple for COUNT. We're still facing the 6th query wrong answer problem.
=> StockLevel fix

src/main/tpcc/tpcc_new_order.cpp, src/main/tpcc/tpcc_payment.cpp, src/main/tpcc/tpcc_workload.cpp
this PR fixed a double-free bug in hard-coded tpcc benchmark.
=> fix bug in tpcc benchmark.

src/include/planner/abstract_plan.h, src/include/planner/aggregate_plan.h, src/include/planner/append_plan.h, src/include/planner/create_plan.h, src/include/planner/delete_plan.h, src/include/planner/drop_plan.h, src/include/planner/hash_join_plan.h, src/include/planner/hash_plan.h, src/include/planner/hybrid_scan_plan.h, src/include/planner/limit_plan.h, src/include/planner/materialization_plan.h, src/include/planner/merge_join_plan.h, src/include/planner/mock_plan.h, src/include/planner/nested_loop_join_plan.h, src/include/planner/order_by_plan.h, src/include/planner/projection_plan.h, src/include/planner/set_op_plan.h, src/optimizer/simple_optimizer.cpp, src/planner/abstract_plan.cpp
This PR fixed the wrong answer problem with OrderByPlan mentioned in [#205].
Now we're able to run NewOrder, Payment, OrderStatus, and StockLevel. However, we're now failing on Delivery on:
UPDATE ORDER_LINE SET OL_DELIVERY_D = $1 WHERE OL_O_ID = $2 AND OL_D_ID = $3 AND OL_W_ID = $4
That issue was not revealed because we had a wrong OrderByPlan before, so we selected nothing to deliver. I'll work on fixing that (hopefully) last issue. I checked other transactions in TPC-C. They at least all run to the end and generate results.
=> Order by fix

src/include/expression/expression_util.h, src/include/planner/abstract_plan.h, src/networking/protocol.cpp, src/planner/abstract_plan.cpp, src/planner/delete_plan.cpp, src/planner/index_scan_plan.cpp, src/planner/seq_scan_plan.cpp, src/planner/update_plan.cpp
This PR fixed the last bug about TPC-C. There're some other jdbc usage fixes in OLTPBench, so you need to pull the latest CMU fork of OLTPBench to run TPC-C:
https://github.com/cmu-db/oltpbench
@yingjunwu @jessesleeping Once this is merged, you can start to run and profile.
=> Fix the generation of ProjectInfo in UpdatePlan.

src/catalog/catalog.cpp, src/catalog/catalog_util.cpp, src/include/catalog/catalog_util.h, src/include/common/exception.h, src/include/common/types.h, src/include/statistics/latency_metric.h, src/include/statistics/processor_metric.h, src/include/statistics/query_metric.h, src/statistics/backend_stats_context.cpp, src/statistics/processor_metric.cpp, src/statistics/query_metric.cpp, src/statistics/stats_aggregator.cpp, test/statistics/stats_test.cpp
=> Add per query CPU utilization stat #295

src/catalog/catalog.cpp, test/executor/inserts_test.cpp, test/executor/update_test.cpp, test/statistics/stats_test.cpp, test/statistics/stats_tests_util.cpp
=> [#302] Remove primary key index creation when there's no primary key.

src/concurrency/timestamp_ordering_transaction_manager.cpp, src/concurrency/transaction.cpp, src/executor/delete_executor.cpp, src/executor/hybrid_scan_executor.cpp, src/executor/index_scan_executor.cpp, src/executor/seq_scan_executor.cpp, src/executor/update_executor.cpp, src/include/common/types.h, src/include/concurrency/timestamp_ordering_transaction_manager.h, src/include/concurrency/transaction.h, src/include/concurrency/transaction_manager.h, src/include/planner/seq_scan_plan.h, src/include/storage/tile_group_header.h, src/storage/tile_group_header.cpp, test/concurrency/select_for_update_txn_test.cpp, test/concurrency/transaction_tests_util.cpp, test/include/concurrency/transaction_tests_util.h
Modify the logic in transaction manager layer to support "select for update". Also add a new test case.
=> Add support for "SELECT ... FOR UPDATE" #224

script/testing/jdbc/src/PelotonTest.java, src/include/common/types.h, src/networking/protocol.cpp
=> Wire protocol bug fix for empty queries (parse & bind) #316

script/testing/jdbc/src/PelotonTest.java, script/testing/nops/gather_nop.sh, script/testing/nops/src/PelotonTest.java, script/testing/nops/test_nop.sh, src/catalog/catalog.cpp, src/executor/plan_executor.cpp, src/include/catalog/schema.h, src/networking/protocol.cpp, src/planner/insert_plan.cpp, src/planner/seq_scan_plan.cpp, src/planner/update_plan.cpp, src/tcop/tcop.cpp, src/wire/libevent_server.cpp
#321 
We should also run full TPCC & YCSB again after this PR.
=> Fix column vector copying during ExecBind

script/testing/nops/src/PelotonTest.java, src/common/varlen_type.cpp, src/executor/plan_executor.cpp, src/networking/protocol.cpp, src/tcop/tcop.cpp
* update nop-test with large update query 
* fix string comparison bug
* fix one more column copy bug
* fix wrong message for bind completion
* reduce string copy in several places in front end 
We should run benchmark on peloton again with the **same** oltpbench client.
=> Many small fixes

src/storage/data_table.cpp
Current implementation did not copy the inserted tuple into the table slot if the slot is recycled by the GC. This PR fixes this bug.
=> fix bug in inserting tuple to data table

src/include/common/value_factory.h, test/common/value_factory_test.cpp
=> Fix getVarchar value length  #332

src/executor/abstract_join_executor.cpp, src/executor/abstract_scan_executor.cpp, src/executor/aggregate_executor.cpp, src/executor/delete_executor.cpp, src/executor/hash_join_executor.cpp, src/executor/hybrid_scan_executor.cpp, src/executor/index_scan_executor.cpp, src/executor/insert_executor.cpp, src/executor/merge_join_executor.cpp, src/executor/nested_loop_join_executor.cpp, src/executor/projection_executor.cpp, src/executor/seq_scan_executor.cpp, src/executor/update_executor.cpp, src/gc/transaction_level_gc_manager.cpp, src/include/common/container_tuple.h, src/include/executor/aggregator.h, src/include/executor/hash_executor.h, src/include/executor/hash_set_op_executor.h, src/main/tpcc/tpcc_delivery.cpp, src/main/tpcc/tpcc_new_order.cpp, src/main/tpcc/tpcc_order_status.cpp, src/main/tpcc/tpcc_payment.cpp, src/main/tpcc/tpcc_stock_level.cpp, src/main/tpcc/tpcc_workload.cpp, src/main/ycsb/ycsb_mixed.cpp, src/storage/tile_group.cpp, src/storage/tile_group_header.cpp, test/common/container_tuple_test.cpp, test/expression/container_tuple_test.cpp
Ultra minor change to close issue #217
=> Moves container_tuple.h to common

src/executor/insert_executor.cpp, src/include/parser/statement_insert.h, src/include/planner/insert_plan.h, src/parser/parser_utils.cpp, src/parser/sql_parser.y, src/planner/insert_plan.cpp, test/executor/inserts_test.cpp, test/parser/parser_test.cpp, test/planner/planner_test.cpp
Supports inserting multiple tuples in the same query. See [#328]
=> [#328] Multi insert

test/common/array_value_test.cpp
Avoid generating a rand string with len = 0
=> Fix random string sef fault issue in array_value_test [#340]

src/include/expression/aggregate_expression.h, src/optimizer/simple_optimizer.cpp, src/tcop/tcop.cpp
=> fix for tpcc after expression refactoring

src/common/init.cpp, src/common/types.cpp, src/include/common/thread_pool.h, src/include/common/types.h, src/include/concurrency/epoch_manager.h, src/include/concurrency/epoch_manager_factory.h, src/include/concurrency/transaction_manager.h, src/wire/libevent_server.cpp
#347 
I will start rewriting epoch manager (which supports read-only transaction) once this PR is merged.
@malin1993ml hope this PR can resolve all the conflicts. Thanks!
=> configurable thread count

CMakeLists.txt, src/include/common/logger.h, src/include/planner/seq_scan_plan.h, src/planner/seq_scan_plan.cpp
I removed this function and all the test cases pass. It's not being used anywhere. Let's just remove it so that it doesn't confuse people. This was for #310
=> Remove Unused SeqScanPlan Constructor

src/include/wire/libevent_server.h, src/include/wire/libevent_thread.h, src/tcop/tcop.cpp, src/wire/libevent_server.cpp, src/wire/libevent_socket.cpp, src/wire/libevent_thread.cpp
I am trying to understand why TPC-C doesn't work. Here are some simple tweaks to refactor the code a bit and to reduce the number of debug messages.
As you can see, I am trying to push stuff in small batches to make sure that my changes don't get lost.
=> Minor LibEvent* Refactoring

src/catalog/catalog.cpp, src/catalog/catalog_util.cpp, src/include/catalog/catalog.h, src/include/planner/seq_scan_plan.h, src/statistics/stats_aggregator.cpp, src/storage/data_table.cpp, src/storage/database.cpp, test/executor/executor_tests_util.cpp, test/executor/join_test.cpp, test/executor/limit_test.cpp, test/executor/loader_test.cpp, test/executor/logical_tile_test.cpp, test/executor/mutate_test.cpp, test/executor/order_by_test.cpp, test/include/executor/executor_tests_util.h, test/index/hybrid_index_test.cpp, test/parser/parser_test.cpp, test/statistics/stats_test.cpp, test/storage/database_test.cpp
=> A bunch of LOG_INFO to LOG_TRACE

src/executor/plan_executor.cpp, src/executor/update_executor.cpp, src/include/storage/data_table.h, src/optimizer/simple_optimizer.cpp, src/storage/data_table.cpp, test/sql/update_secondary_index_sql_test.cpp
This PR fixed the secondary index issue: cannot find tuple after updating, that is described in the comment of #384 (but #384 is still there).
=> Fix secondary index issue: cannot find tuple after updating

src/executor/update_executor.cpp, src/include/executor/update_executor.h, src/include/planner/update_plan.h, src/planner/update_plan.cpp, test/sql/update_primary_index_sql_test.cpp
=> Fix pkey update issue

.travis.yml, src/main/tpcc/tpcc_loader.cpp, src/main/ycsb/ycsb_loader.cpp
=> Fix ycsb and tpc-c compilation

src/brain/layout_tuner.cpp, src/include/brain/layout_tuner.h, src/include/storage/data_table.h, src/storage/data_table.cpp, test/brain/layout_tuner_test.cpp
This PR contains:
- Tests for layout tuner
- Tests for index tuner
=> Added Tuner Tests

src/brain/index_tuner.cpp, src/include/storage/tile_group.h, src/storage/tile_group.cpp, test/brain/index_tuner_test.cpp, test/brain/layout_tuner_test.cpp, test/common/container_tuple_test.cpp, test/index/hybrid_index_test.cpp, third_party/valgrind/valgrind.supp
- This PR adds more checks in tuner tests. Finished testing index and layout tuners.
=> Updated tuner tests

src/brain/index_tuner.cpp, src/brain/layout_tuner.cpp, src/include/storage/data_table.h, src/storage/data_table.cpp, test/brain/layout_tuner_test.cpp, third_party/valgrind/valgrind.supp
This PR reenables the layout tuner test.
=> Fix layout tuner test

src/executor/aggregate_executor.cpp
=> Fix an unused variable in the release build.

script/oltpbenchmark/testbed/ReadMe.md, script/oltpbenchmark/testbed/gather_tpcc.sh, script/oltpbenchmark/testbed/gather_ycsb.sh, script/oltpbenchmark/testbed/measure-performance-tpcc.py, script/oltpbenchmark/testbed/measure-performance-ycsb.py, script/oltpbenchmark/testbed/tpcc_template.xml, script/oltpbenchmark/testbed/ycsb_template.xml
Scripts I used to profile the system.
=> Add oltpbench scripts

src/common/cache.cpp, src/include/common/cache.h, src/include/type/types.h, src/include/wire/marshal.h, src/include/wire/packet_manager.h, src/networking/protocol.cpp, src/type/types.cpp, src/wire/marshal.cpp
=> [wire] Close + Serialization error reporting

script/testing/jdbc/src/PelotonTest.java, script/validators/jdbc_validator.py, src/gc/gc_manager_factory.cpp, src/gc/transaction_level_gc_manager.cpp, src/include/gc/gc_manager.h, src/include/gc/gc_manager_factory.h, src/include/gc/transaction_level_gc_manager.h, src/storage/abstract_table.cpp, src/storage/database.cpp, test/include/common/harness.h
=> turn on garbage collection

src/executor/index_scan_executor.cpp, src/optimizer/simple_optimizer.cpp
=> fix the secondary key issue: update checking index

CMakeLists.txt, script/validators/validator.py, src/executor/abstract_executor.cpp, src/executor/index_scan_executor.cpp, src/include/executor/abstract_executor.h, src/include/executor/index_scan_executor.h, src/include/index/bwtree.h, src/include/index/bwtree_index.h, src/include/index/index.h, src/include/optimizer/simple_optimizer.h, src/include/planner/index_scan_plan.h, src/index/bwtree.cpp, src/index/bwtree_index.cpp, src/index/index_factory.cpp, src/optimizer/simple_optimizer.cpp, test/optimizer/simple_optimizer_test.cpp
This PR optimizes the sql statement with order by limit 1 and also merged ziqi's new BwTree. A simple performance test is done and the result shows that the performance is improved a lot! Let's test the true performance after merging this PR with master.
=> Fix Limit issue and merge with new BwTree

src/executor/plan_executor.cpp
Removed unneccesary copying and retrieval of output schema
=> Simple Optimizations to PlanExecutor

src/brain/index_tuner.cpp, test/brain/index_tuner_test.cpp
This PR focuses on tuner integration.
=> Tuner integration

src/catalog/catalog.cpp, src/include/storage/data_table.h, src/include/storage/table_factory.h, src/storage/data_table.cpp, src/storage/table_factory.cpp, test/executor/loader_test.cpp, test/performance/insert_performance_test.cpp
This PR includes the following features:
1. do not preallocate multiple tile groups for catalog tables;
=> reduce memory usage of catalog tables

src/include/storage/tile_group_header.h
simple yet effective optimization.
=> reduce reserved field size

script/pre_commit/pre-commit.sh, script/pre_commit/pre_commit.md, test/sql/drop_sql_test.cpp
=> add instructions for installing pre-commit hook

src/expression/date_functions.cpp, test/expression/date_functions_test.cpp
https://www.youtube.com/watch?v=rRN08dfQIn8
=> Project 1 Test Case Fix

src/optimizer/simple_optimizer.cpp
I forgot to add some refactoring from the review
=> Further refactoring of the order_by functions

src/type/type.cpp, test/type/type_test.cpp
Simple test case for INVALID type. We were not checking these before and it turns out that we were not throwing exceptions correctly.
http://i.imgur.com/NuNbW1X.gifv
=> Invalid Type Tests

script/installation/Vagrantfile
This allows working on the host without having to sync every change to VM.
=> Link repo work dir on host into VM instead of cloning

src/main/sdbench/sdbench.cpp, src/main/sdbench/sdbench_loader.cpp
=> fix bugs in sdbench

src/include/parser/postgresparser.h, src/parser/postgresparser.cpp, test/parser/postgresparser_test.cpp
Change the casts to reinterpret_cast and NULL to nullptr.
=> Change PostgresParser to use c++-style

src/parser/postgresparser.cpp, src/type/types.cpp, test/parser/postgresparser_test.cpp
This PR is for PostgresParser and it contains:
- Added support for SELECT from multiple sources
- Added support for HAVING clauses in GROUP BY clauses
- Added more support for AExpr tranformation(support for 1 + 1 and col + 1)
=> Support multiple sources for SELECT and HAVING clause

cmake/Dependencies.cmake, src/planner/insert_plan.cpp, test/planner/planner_test.cpp
now planner_test compiles and passes once again.
=> proper parameter indexing in insert plans v2

src/type/bigint_type.cpp
=> fix bigint serialization

src/executor/copy_executor.cpp, src/include/executor/copy_executor.h
Copy executor should not dependent on logging. 
@malin1993ml Please help review this PR. Thanks!
=> remove dependency on logging component

script/installation/packages.sh
This is for #663 
https://www.youtube.com/watch?v=XMe0PTYDnXw
=> Fixed packages script install custom repo for llvm-3.7 on Ubuntu 14.04

src/codegen/case_translator.cpp, src/codegen/codegen.cpp, src/codegen/constant_translator.cpp, src/codegen/translator_factory.cpp, src/codegen/values_runtime.cpp, src/common/sql_node_visitor.cpp, src/include/codegen/case_translator.h, src/include/codegen/codegen.h, src/include/common/sql_node_visitor.h, src/include/expression/case_expression.h, src/include/expression/expression_util.h, src/include/parser/parsenodes.h, src/include/parser/postgresparser.h, src/parser/postgresparser.cpp, test/codegen/case_translator_test.cpp, test/expression/expression_test.cpp, test/parser/postgresparser_test.cpp, test/sql/case_sql_test.cpp
This patch adds a fix on the current parser.  The previous test scenario in #548 is tested and I added some scenarios including those mentioned in #553.
=> Issue #548, #553 - CASE works with SELECT

src/wire/libevent_callbacks.cpp, src/wire/libevent_socket.cpp, src/wire/marshal.cpp
I still think that this one of the best videos of all time:
https://www.youtube.com/watch?v=5E6WM19r6V8
=> Switched LOG_INFO debug messages in the wire protocol to LOG_TRACE

src/brain/index_tuner.cpp, src/wire/packet_manager.cpp
Fix #681 by deleting the split-query statement and for loop, since the query has already been parsed and split by PostgreSQL client.
=> Fix issue semi-colon bug.

script/installation/Vagrantfile
I've modified the Vagrant file to pass all along SSE 4.1 and 4.2 features to VirtualBox. 
This is for #706.
=> Pass CPU features to VirtualBox

.travis.yml
This PR contains the new Travis file which builds the following configurations:
GCC-4.9
- Debug
- Release
GCC-5.4
- Debug (with coveralls)
- Release
=> Adding new build targets for travis

.travis.yml
https://www.youtube.com/watch?v=6fYfvjdBOi8
=> Re-enable the psql tests in travis.yml

src/include/optimizer/util.h, src/optimizer/optimizer.cpp, src/optimizer/util.cpp, test/executor/copy_test.cpp
This PR supports COPY  statement in the new optimizer. It follows the same logics of CreateCopyPlan in the simple optimizer.
=> Support COPY in the new optimizer

src/binder/binder_context.cpp, src/catalog/abstract_catalog.cpp, src/catalog/catalog.cpp, src/catalog/catalog_storage_manager.cpp, src/codegen/proxy/catalog_proxy.cpp, src/codegen/query.cpp, src/codegen/util/sorter.cpp, src/include/catalog/catalog.h, src/include/catalog/catalog_storage_manager.h, src/include/storage/backend_manager.h, src/include/storage/storage_manager.h, src/optimizer/stats/stats_storage.cpp, src/planner/seq_scan_plan.cpp, src/statistics/backend_stats_context.cpp, src/statistics/index_metric.cpp, src/statistics/stats_aggregator.cpp, src/statistics/table_metric.cpp, src/storage/backend_manager.cpp, src/storage/data_table.cpp, src/storage/storage_manager.cpp, src/storage/table_factory.cpp, src/storage/tile.cpp, src/storage/tile_group_header.cpp, test/catalog/catalog_test.cpp, test/concurrency/testing_transaction_util.cpp, test/gc/garbage_collection_test.cpp, test/gc/transaction_level_gc_manager_test.cpp, test/storage/backend_manager_test.cpp, test/storage/database_test.cpp
This PR starts to separate the catalog logic between catalog stuff (catalog.cpp) and physical data stuff (catalog_storage_manager.cpp). It's mostly moving things to another class and adapting the rest of the system to work along.
- `TestingTransactionUtil` uses the catalog database by default, so catalog must be initialized, even if it's not used (refactor candidate)?
=> Beginning work on CatalogStorageManager

src/binder/bind_node_visitor.cpp, src/catalog/abstract_catalog.cpp, src/include/binder/bind_node_visitor.h, src/include/expression/expression_util.h, src/include/optimizer/optimizer.h, src/tcop/tcop.cpp, src/wire/packet_manager.cpp, test/binder/binder_test.cpp, test/executor/create_index_test.cpp, test/executor/delete_test.cpp, test/executor/index_scan_test.cpp, test/executor/update_test.cpp, test/include/statistics/testing_stats_util.h, test/optimizer/optimizer_rule_test.cpp, test/optimizer/optimizer_test.cpp, test/sql/aggregate_sql_test.cpp, test/sql/analyze_sql_test.cpp, test/sql/case_sql_test.cpp, test/sql/distinct_sql_test.cpp, test/sql/drop_sql_test.cpp, test/sql/optimizer_sql_test.cpp, test/sql/order_by_sql_test.cpp, test/sql/projection_sql_test.cpp, test/sql/testing_sql_util.cpp, test/sql/update_secondary_index_sql_test.cpp, test/sql/update_sql_test.cpp, test/statistics/testing_stats_util.cpp
This PR add support for SQL case and fully switch to new optimizer. The NEW_OPTIMIZER flag in tcop is kept for potential need for using SimpleOptimizer.
=> Tearing down SimpleOptimizer

src/concurrency/timestamp_ordering_transaction_manager.cpp, src/concurrency/transaction_manager.cpp, src/executor/delete_executor.cpp, src/gc/transaction_level_gc_manager.cpp, src/include/concurrency/transaction_manager.h, src/include/gc/transaction_level_gc_manager.h, src/include/type/types.h, src/storage/storage_manager.cpp, src/type/types.cpp, test/gc/garbage_collection_test.cpp, test/gc/transaction_level_gc_manager_test.cpp, test/type/types_test.cpp
The insertion/deletion bugs reported recently are mostly related to the design of GC manager. This PR tries to fundamentally solve this problem by redesigning the GC component.
=> fix visibility bug

script/validators/source_validator.py, src/include/parser/parser_utils.h, src/include/parser/sql_statement.h, src/include/type/types.h, src/parser/parser_utils.cpp, src/parser/sql_statement.cpp, src/type/types.cpp, test/parser/parser_utils_test.cpp
This is the fix for issue #736 and contains:
- Creation of new ParserUtils class
- Migration of the utils from printing out to building a string for the target statement
- Addition of utils for Update and Copy statements
- Removal of related files from validator skipping list
- Some tests for the parser utils
=> Fix for Issue #736

src/catalog/multi_constraint.cpp, src/catalog/trigger_catalog.cpp, src/executor/delete_executor.cpp, src/executor/insert_executor.cpp, src/executor/update_executor.cpp, src/include/catalog/multi_constraint.h, src/include/catalog/trigger_catalog.h, src/include/storage/data_table.h, src/include/trigger/trigger.h, src/include/util/file_util.h, src/include/util/string_util.h, src/include/util/stringbox_util.h, src/storage/data_table.cpp, src/trigger/trigger.cpp, src/util/string_util.cpp, test/executor/create_test.cpp, test/executor/delete_test.cpp
I noticed triggers were using raw pointers and `new`. This PR fixes it to use smart pointers. I also formatted some code, updated licenses, and fixed namespace closures.
=> Use smart pointers in triggers

src/catalog/abstract_catalog.cpp, src/executor/plan_executor.cpp, src/storage/tuple.cpp
Fix the errors mentioned in the issue `810`
=> Fix builds with LOG_LEVEL_TRACE

script/testing/sqlite_trace/config.py, script/testing/sqlite_trace/run.sh, script/testing/sqlite_trace/trace-replay.py
Modify sqlite testing script to work with jenkins configuration and fetch a built version of the testing framework instead of the source code.
=> SQLite test trace fix

src/executor/copy_executor.cpp, src/include/common/logger.h, src/include/optimizer/stats/histogram.h, src/optimizer/column_manager.cpp, src/optimizer/stats/column_stats_collector.cpp, src/optimizer/util.cpp, src/storage/tuple.cpp
https://www.youtube.com/watch?v=OxvgqUHaKtY
Simple fixes. I decided to put `#include <inttypes.h>` in `common/logger.h`. Not sure if this okay for now.
=> LOG_TRACE fixes after switching Type::TypeId to an 'enum class'

src/codegen/compilation_context.cpp, src/codegen/query.cpp, src/include/optimizer/cost_and_stats_calculator.h, src/include/optimizer/stats.h, src/include/optimizer/stats/cost.h, src/include/optimizer/stats/table_stats.h, src/optimizer/cost_and_stats_calculator.cpp, src/optimizer/stats/cost.cpp, src/optimizer/stats/table_stats.cpp, src/traffic_cop/traffic_cop.cpp, test/optimizer/cost_and_stats_calculator_test.cpp, test/optimizer/cost_test.cpp
- Let Stat be the base class of TableStat
- Move some variables and functions inside Cost class to avoid linking problem
- Add cost_and_stats_calculator_test with a simple test case of testing the seqscan
=> implement cost_and_stats_calculator

test/README.md
Added info for Usage of TestingExecutorUtil to create tables
=> Updating the README of /test/

script/testing/sqlite_trace/trace-replay.py
=> Expose some command line arguments for the testing script.

src/catalog/catalog.cpp, src/codegen/expression/comparison_translator.cpp, src/codegen/proxy/string_functions_proxy.cpp, src/codegen/translator_factory.cpp, src/codegen/type/varchar_type.cpp, src/function/string_functions.cpp, src/include/codegen/proxy/string_functions_proxy.h, src/include/function/string_functions.h, src/include/type/types.h, test/function/string_functions_test.cpp, test/sql/type_sql_test.cpp
This PR is blocked by the varchar length bug. Once the bug is fixed we will add more sql tests.
=> Add LIKE function

src/binder/binder_context.cpp, src/catalog/abstract_catalog.cpp, src/catalog/catalog.cpp, src/catalog/catalog_cache.cpp, src/catalog/column_catalog.cpp, src/catalog/database_catalog.cpp, src/catalog/index_catalog.cpp, src/catalog/table_catalog.cpp, src/catalog/trigger_catalog.cpp, src/executor/create_executor.cpp, src/include/catalog/column_catalog.h, src/include/catalog/database_catalog.h, src/include/catalog/index_catalog.h, src/include/catalog/table_catalog.h, src/optimizer/optimizer.cpp, src/optimizer/stats/selectivity.cpp, src/trigger/trigger.cpp, test/catalog/catalog_test.cpp, test/codegen/testing_codegen_util.cpp, test/executor/create_test.cpp
Issue #859: Better support for "what-if" optimizer API in catalog objects.
@malin1993ml Sorry for the delay. I was busy with something else earlier. Let me know if you need anything else.
=> Fixing access pattern for catalog objects for Issue #859

src/storage/data_table.cpp
This PR fixes #938. It used to check the constraints only when a tuple is newly inserted. This PR also checks them at `InsertVersion()`, which is essentially called at UPDATE.
Note: After updating a tuple which violates the constraints, it produces an exception as in INSERT, however, the exception is correctly caught and the peloton instance gets **aborted**.  This is a another bug which is not related to this, but to be solved.
[SQL session]
```
postgres=# create table test (a int, b int not null);
CREATE TABLE
postgres=# insert into test values(null, 1);
INSERT 0 1
postgres=# update test set b=a;
```
[Peloton output]
```
Exception Type :: Constraint
Message :: NOTNULL constraint violated on column 'b' : FIXME
terminate called after throwing an instance of 'peloton::ConstraintException' …
```
=> Check constraints while updating a tuple

src/include/traffic_cop/traffic_cop.h, src/traffic_cop/traffic_cop.cpp
Cleanup as I work on the callback-based multi-threading stuff.
This is a separate clean up PR, mostly just code formatting. No interface changes at all.
=> [Cleanup] Cleanup TrafficCop, mostly formatting

test/catalog/catalog_test.cpp, test/codegen/parameterization_test.cpp, test/codegen/query_cache_test.cpp, test/common/cache_test.cpp, test/concurrency/local_epoch_test.cpp, test/executor/copy_test.cpp, test/index/index_util_test.cpp, test/logging/buffer_pool_test.cpp, test/logging/checkpoint_test.cpp, test/logging/log_buffer_test.cpp, test/logging/logging_util_test.cpp, test/logging/recovery_test.cpp, test/network/rpc_client_test.cpp, test/network/rpc_queryplan_test.cpp, test/network/rpc_server_test.cpp, test/network/simple_query_test.cpp, test/optimizer/table_stats_test.cpp, test/parser/parser_test.cpp, test/settings/settings_manager_test.cpp, test/storage/tile_group_test.cpp, test/type/date_value_test.cpp, test/type/timestamp_value_test.cpp
All the EXPECT_EQ statements for boolean values have now been changed to EXPECT_TRUE & EXPECT_FALSE
=> [Cleanup] Change boolean EXPECT_EQs to EXPECT_TRUE & EXPECT_FALSE

src/include/common/exception.h, src/include/network/connection_handle.h, src/include/network/connection_handle_factory.h, src/include/network/error_util.h, src/include/network/network_state.h, src/include/network/notifiable_task.h, src/network/connection_handle.cpp, test/network/prepare_stmt_test.cpp
This is the last network layer refactor PR. I mainly worked on improving error handling using wrappers and exceptions. There is much unfinished work but I should have gotten to most things above protocol handler.
Protocol Handler and traffic cop are both so complicated we probably need a summer rewriting them (if we ever want to)
=> Improved network error handling

src/binder/bind_node_visitor.cpp, src/catalog/catalog.cpp, src/executor/drop_executor.cpp, src/include/executor/drop_executor.h, src/include/parser/create_statement.h, src/include/parser/drop_statement.h, src/include/parser/parsenodes.h, src/include/parser/postgresparser.h, src/include/parser/sql_statement.h, src/include/planner/drop_plan.h, src/parser/postgresparser.cpp, src/planner/create_plan.cpp, src/planner/drop_plan.cpp, test/executor/drop_test.cpp, test/parser/parser_test.cpp, test/planner/planner_test.cpp, test/sql/optimizer_sql_test.cpp
Fix the drop database executor that previously only drop database from default databases;
Add drop database function.
=> Drop executor fix

script/installation/packages.sh
=> Fix packages.sh execution on Ubuntu 15.x and 16.x

script/validators/source_validator.py, test/optimizer/optimizer_test.cpp
This PR adds more checks to the source validator as requested in #770. 
1. **Make sure that the namespace is properly commented (#768)**
The check works, but all namespace checks are still disabled, until refactoring is finished (see #968)
2. **Make sure that we don't have the prefix "include/" in our own #include's**
PR also includes commit that fixes violating files. 
The second request in #770 "Make sure that testing utility files follow the proper naming convention" is still missing. Also the checks are added to the source validator and **not** in the formatter.
=> [Cleanup] Add more checks in source validator

src/function/old_engine_string_functions.cpp, src/include/function/old_engine_string_functions.h
Adding stub functions for upper/lower so functions can be registered in catalog. Needed for 15-721.
=> 15-721: Stub functions in old engine for upper/lower

.travis.yml, Jenkinsfile, script/docker/debian-stretch/Dockerfile-jenkins, script/installation/packages.sh
Correct the Jenkins build pipelines to run all builds in Docker, including the test generation stage.  The results of this pipeline should be interpreted as true results.  Platforms known to be not working at this time are commented out.
=> Jenkins (for real this time)

script/github/github-pr-status.py, script/github/github-stats.py
These scripts are used to update the homepage and send out the PR status report.
=> Python Scripts for Retriving Github Information

CMakeLists.txt, script/installation/packages.sh, src/include/common/exception.h, src/include/index/sorted_small_set.h, src/include/type/value_factory.h
This PR has the necessary fixes to get the system to build + run on Ubuntu 17.10. There was a problem with getting C++11 to work correctly where you have to add compiler directives. From what I can tell online this seems to be a problem specific to g++5.4, so I limited the fix to just that version.
Note that I added the header to 'value_factory.h' and for some reason it changed every line.
https://www.youtube.com/watch?v=b0MFNM9oOoU
=> Support Ubuntu 17.10

Jenkinsfile
requested by @pervazea, addresses #1184
=> remove the ||true from make check

script/installation/packages.sh
These are tensorflow specific improvements to the `packages.sh` script.
Added the following:
1. Fix for Mac `tar -C` error occuring on recent OSX versions.
2. Fix for `pip install` within a proxy environment.
3. Cleanup of bloated downloads post installation.
4. `wget` brew installation.
=> Improvements to 'packages.sh'

Jenkinsfile
=> disable Fedora 27 per #1204

script/installation/packages.sh
also, format the function bodies while here.
This is in support of #1317
=> only install TF and newer protobuf if they're not already installed

src/include/planner/hybrid_scan_plan.h, src/include/planner/index_scan_plan.h, src/planner/hybrid_scan_plan.cpp, src/planner/index_scan_plan.cpp
Apparently I forgot to delete the now unused index_predicate_ in IndexScanPlan and HybridScanPlan in #1301. This PR fixes that.
=> Delete the unsed index_predicate_ in index scan plans.

src/main/peloton/peloton.cpp, src/network/peloton_server.cpp
it's for this issue : Socket bind failure handling #1277 
when 'bind' fails, log error message and exit with none-zero value
=> fix #1277 Socket bind failure handling

src/catalog/manager.cpp, src/concurrency/timestamp_ordering_transaction_manager.cpp, src/concurrency/transaction_manager.cpp, src/executor/delete_executor.cpp, src/executor/hybrid_scan_executor.cpp, src/executor/index_scan_executor.cpp, src/executor/update_executor.cpp, src/gc/transaction_level_gc_manager.cpp, src/include/catalog/manager.h, src/include/storage/storage_manager.h, src/main/tpcc/tpcc_workload.cpp, src/main/ycsb/ycsb_workload.cpp, src/statistics/backend_stats_context.cpp, src/storage/data_table.cpp, src/storage/storage_manager.cpp, src/storage/tile_group.cpp, test/catalog/manager_test.cpp, test/executor/testing_executor_util.cpp, test/storage/tile_group_test.cpp
Move tile group related code from catalog manager to storage manager as what had been done in PR#1376.
=> Move tile group related code from catalog manager to storage manager

.travis.yml
Small fix in travis config that should reenable Coveralls testing.
=> Coveralls fix

script/installation/packages.sh
=> Resolve Protobuf early exit

src/codegen/operator/table_scan_translator.cpp, src/codegen/proxy/transaction_runtime_proxy.cpp, src/codegen/transaction_runtime.cpp, src/include/codegen/proxy/transaction_runtime_proxy.h, src/include/codegen/transaction_runtime.h
I did the fixes suggested in #1386. Be gentle, it's my first time touching codegen :)
=> fix #1386: PerformVectorizedRead optimization

src/network/network_io_wrapper_factory.cpp
=> Fix ssl copy bug

src/common/container/cuckoo_map.cpp, src/common/init.cpp, src/common/internal_types.cpp, src/concurrency/timestamp_ordering_transaction_manager.cpp, src/gc/transaction_level_gc_manager.cpp, src/include/common/internal_types.h, src/include/gc/gc_manager.h, src/include/gc/transaction_level_gc_manager.h, src/include/storage/data_table.h, src/include/storage/tile_group.h, src/storage/data_table.cpp, test/common/internal_types_test.cpp, test/concurrency/testing_transaction_util.cpp, test/executor/loader_test.cpp, test/gc/garbage_collection_test.cpp, test/gc/transaction_level_gc_manager_test.cpp, test/include/concurrency/testing_transaction_util.h, test/performance/insert_performance_test.cpp, test/sql/update_sql_test.cpp
This reverts commit b693494
The combination of this PR and #1455 manifests a segfault in YCSB that we dont yet understand. Reverting in the meantime.
=> Revert "Garbage collection fixes (#1428)"
