- src/backend/expression/abstract_expression.cpp
- src/backend/expression/case_expression.h
See discussion in #80 
A better approach would be using shared_ptr. I have already changed it in expression part. However the logic of transforming CaseExpr disappears in master branch, therefore I did not push this update.
> Set the objects as nullptr in destructor

- src/backend/concurrency/optimistic_transaction_manager.cpp
- tests/concurrency/transaction_test.cpp
To write transaction tests easily, I added several helpers in `transaction_test.cpp`. Now one can describe schedule of operations (insert,delete,update,read) of a transaction in a simple way.
> Add transaction test helpers

- src/backend/bridge/dml/mapper/mapper.cpp
I got an exception when executing this query:
`SELECT 1 FROM A WHERE id IN (SELECT id FROM A)`
The reason is very similar to what we have discussed before: our code did not set to nullptr after deletion.
> Fix bug in cleaning plan

- .gitignore
- src/backend/expression/abstract_expression.h
- src/backend/expression/case_expression.h
- src/backend/expression/cast_expression.h
- src/backend/expression/coalesce_expression.h
- src/backend/expression/comparison_expression.h
- src/backend/expression/conjunction_expression.h
- src/backend/expression/constant_value_expression.h
- src/backend/expression/date_expression.h
- src/backend/expression/expression_util.h
- src/backend/expression/function_expression.cpp
- src/backend/expression/hash_range_expression.h
- src/backend/expression/nullif_expression.h
- src/backend/expression/operator_expression.h
- src/backend/expression/parameter_value_expression.h
- src/backend/expression/scalar_value_expression.h
- src/backend/expression/string_expression.h
- src/backend/expression/string_functions.h
- src/backend/expression/subquery_expression.h
- src/backend/expression/tuple_address_expression.h
- src/backend/expression/tuple_value_expression.h
- src/backend/expression/vector_comparison_expression.h
- src/backend/expression/vector_expression.h
- tests/expression/expression_test.cpp
In order to support intra-query parallelism, peloton plan tree has to be copied. During copy, the difficult but necessary part is to copy expression classes. 
In this commit, AbstractExpression is added a Copy interface, like following:
`  virtual AbstractExpression *Copy() const = 0;`
Each child class of AbstractExpression  implements this interface, and do recursively copy in a clean manner.
In expression_test, the old tests are extended, to test if copied expressions are correct.
> Add copy functions to expressions.

- src/backend/planner/abstract_join_plan.h
- src/backend/planner/abstract_plan.h
- src/backend/planner/abstract_scan_plan.h
- src/backend/planner/aggregate_plan.h
- src/backend/planner/append_plan.h
- src/backend/planner/delete_plan.h
- src/backend/planner/hash_join_plan.h
- src/backend/planner/hash_plan.h
- src/backend/planner/index_scan_plan.h
- src/backend/planner/insert_plan.h
- src/backend/planner/limit_plan.h
- src/backend/planner/materialization_plan.h
- src/backend/planner/merge_join_plan.h
- src/backend/planner/mock_plan.h
- src/backend/planner/nested_loop_join_plan.h
- src/backend/planner/order_by_plan.h
- src/backend/planner/project_info.h
- src/backend/planner/projection_plan.h
- src/backend/planner/result_plan.h
- src/backend/planner/seq_scan_plan.h
- src/backend/planner/set_op_plan.h
- src/backend/planner/update_plan.h
As we discussed in #110, the interface changed as follow:
`std::unique_ptr<AbstractPlan> Copy() const = 0`
> Change plan copy interface 

- src/backend/concurrency/speculative_read_txn_manager.cpp
This bug may cause incorrect result when performing aggregation operations with speculative-read OCC.
> fix a bug in occ with speculative read.

- src/backend/executor/aggregate_executor.cpp
- src/backend/executor/aggregator.cpp
- src/backend/executor/logical_tile_factory.cpp
- src/backend/executor/logical_tile_factory.h
- src/backend/storage/tile_group.cpp
- src/backend/storage/tile_group.h
- src/backend/storage/tile_group_header.cpp
- src/backend/storage/tile_group_header.h
- tests/executor/aggregate_test.cpp
- tests/executor/append_test.cpp
- tests/executor/hash_set_op_test.cpp
- tests/executor/join_test.cpp
- tests/executor/limit_test.cpp
- tests/executor/order_by_test.cpp
- tests/executor/projection_test.cpp
- tests/executor/seq_scan_test.cpp
- tests/logging/checkpoint_test.cpp
- tests/storage/tile_group_test.cpp
In `tile_group_header` class, the function `GetActiveTupleCount()` is called only when building tile groups for aggregation operations. As such temporal tile groups are privately owned by a single transaction, the implementation is simplified.
> modify tile group header api

- src/backend/bridge/dml/mapper/mapper_agg.cpp
- src/backend/bridge/dml/mapper/mapper_hash_join.cpp
- src/backend/bridge/dml/mapper/mapper_merge_join.cpp
- src/backend/bridge/dml/mapper/mapper_nested_loop_join.cpp
This following statement fails:
```
SELECT count(*) FROM a, b, c, d
```
because `project_info` is a nullptr and our code did not handle it properly.
> Fix bug in handling empty project_info in plan transformers

- src/backend/common/worker_thread_pool.h
Currently, every time a query session is created, a thread is spawned and detached. however, this is quite inefficient when processing massive number of transactions. We may use a thread pool that can reuse threads efficiently. Due to the lack of efficient thread pool, I added boost thread pool in this pr for future usage.
> add boost thread pool

- src/backend/bridge/dml/expr/expr_transformer.cpp
- src/backend/bridge/dml/expr/expr_transformer.h
- src/backend/bridge/dml/mapper/dml_utils.cpp
- src/backend/bridge/dml/mapper/dml_utils.h
- src/backend/bridge/dml/tuple/tuple_transformer.cpp
- src/backend/expression/date_functions.h
- src/postgres/backend/postmaster/peloton.cpp
- src/postgres/include/postmaster/peloton.h
This PR mainly fixes the bug in issue #143.
As mentioned in that post, Postgres uses generic plan after several rounds of execution. In a generic plan, a parameter will be filled with a `Param` node rather than a `Const` node, and will be replaced by runtime_key in executor. However, Peloton does not handle some data types correctly (like strings and lists) when transforming the `Param` node.
This PR first fixes the bug in handling text, varchar, bpchar. What we do here is to simply transform it to an empty Value, since it will be replaced by runtime key anyway.
Things are more complicated for arrays. An `ArrayExpr` is passed as `runtime_key`, and Peloton does not support transforming `ArrayExpr` now. <del>Since this is sort of independent issue, I will send a separate PR when I finish …
> fix bug in transforming empty strings in scan key

- src/backend/benchmark/tpcc/tpcc_workload.cpp
- src/backend/bridge/dml/expr/expr_transformer.cpp
- src/backend/expression/expression_util.cpp
- src/backend/expression/expression_util.h
- src/backend/expression/udf_expression.h
- src/backend/logging/checkpoint/simple_checkpoint.cpp
- src/backend/logging/loggers/wal_frontend_logger.cpp
- src/backend/storage/data_table.cpp
- tests/logging/recovery_test.cpp
Three things are fixed in this PR:
1. UDF expressions do not clean up their argument expressions. Fixed by using `unique_ptr`. This should've been caught in code review. 
2. Fixed more LOG_TRACE statement formats.
3. Explicitly set logging directory in recovery test so that is passes in debug builds.
Let me know if anything is amiss.
> Fixed memory leak in UDF expressions

- src/common/types.cpp
- src/executor/delete_executor.cpp
- src/executor/index_scan_executor.cpp
- src/executor/logical_tile.cpp
- src/executor/update_executor.cpp
- src/include/common/abstract_tuple.h
- src/include/common/types.h
- src/include/executor/logical_tile.h
- src/include/expression/container_tuple.h
- src/include/planner/project_info.h
- src/include/storage/data_table.h
- src/include/storage/tile_group.h
- src/include/storage/tuple.h
- src/planner/project_info.cpp
- src/storage/data_table.cpp
- src/storage/tile_group.cpp
- src/storage/tuple.cpp
- test/concurrency/isolation_level_test.cpp
currently, Peloton suffers from high memory allocation overhead when performing update operations. The key reason is that `update_executor` will always create a temporal copy for holding results obtained from tuple projection. This PR avoids creating such copy by directly performing in-place update on tuple versions. Every time the DBMS updates a tuple, it will (1) acquire a version slot from data table; (2) perform projection; (3) install the version back to data table.
btw, our itempointer pointer design is not the key factor for high memory allocation overhead. In fact, such allocation is cheap.
> reduce memory allocation

- src/executor/hybrid_scan_executor.cpp
- src/executor/index_scan_executor.cpp
- src/executor/seq_scan_executor.cpp
- src/logging/checkpoint/simple_checkpoint.cpp
- src/logging/loggers/wal_frontend_logger.cpp
- test/logging/checkpoint_test.cpp
The master branch failed to build with g++ 5. This is caused by the missing of `numeric` library. This PR fixes this problem.
> quick fix compilation failure with g++ 5

- .travis.yml
- script/installation/packages.sh
- script/testing/dml/basic1.sql
- script/testing/psql/psql_ref_out.txt
- script/testing/psql/psql_test.sh
I have added tests into CI to test if PSQL works.
1. The installation script has been updated to install the postgresql-client apt package to get psql "out-of-the-box"
2. The test_jdbc.sh script runs script/testing/dml/basic1.sql and diff's the output with the reference output for validation
3. Travis has been updated to include this test script into CI
EDIT: I also changed test ports because Travis has postgres installed by default and Peloton and Postgres currently use the same default port.
> #229: added CI test for psql

- script/testing/jdbc/src/PelotonTest.java
- src/planner/index_scan_plan.cpp
The values of a IndexScanPlan are copied when binding a new query. That was implicitly done when copying a vector with value objects.
Now since we're using value pointers, we need to do deep copy manually.
> [#241] Fix the copying of values when binding IndexScanPlan.

- script/testing/jdbc/src/PelotonTest.java
- src/parser/sql_parser.y
This fix gives the "*" in count(*) a name.  before it was null, causing a segfault.
I also add back in the aggregate, and batch tests.
We might want to add aggregation functions to the parser,
rather than having a generic "function". We currently check for
aggregate functions by string matching function names to find "min",
"max", etc. in the optimizer. We have expression types for these
aggregate functions but don't use them.
> [#242] Fixed count(*) failing an assertion in tcop.cpp (null pointer)

- src/main/tpcc/tpcc_delivery.cpp
- src/main/tpcc/tpcc_loader.cpp
- src/main/tpcc/tpcc_new_order.cpp
- src/main/tpcc/tpcc_payment.cpp
- src/main/tpcc/tpcc_workload.cpp
In this PR, I fixed a type-system-related problem in the hard-coded version of TPC-C benchmark. In our current implementation, the data value is created outside of the `IndexScanPlan` but deleted by the deconstructor of the `IndexScanPlan` (which is not a very good habit). This forbids us from reusing the created values.
> fix bug in tpcc benchmark

- test/statistics/stats_tests_util.cpp
Annotate the unused variable which breaks the release jenkins build.
> Fix unused variable in stat test. #271

- test/CMakeLists.txt
Adding this flag will generate one XML output for every gtest target. I didn't find the documentation of generating a single XML file for all the tests. #275
> [#275] Add XML output flag for gtest.

- script/testing/jdbc/src/PelotonTest.java
- src/executor/plan_executor.cpp
- src/executor/seq_scan_executor.cpp
This diff pulls the output logical tiles even when Execute() status is true. This ensures that all the tiles will be returned for queries that generate output spanning over multiple logical tiles.
> #291 Fixed multi-tile group output collection

- script/testing/jdbc/src/PelotonTest.java
- src/catalog/catalog.cpp
- src/include/catalog/catalog.h
- src/include/storage/data_table.h
- src/include/storage/database.h
- src/networking/protocol.cpp
- src/optimizer/simple_optimizer.cpp
- src/planner/drop_plan.cpp
- src/statistics/index_metric.cpp
- src/statistics/table_metric.cpp
- src/storage/data_table.cpp
- src/storage/database.cpp
- src/storage/table_factory.cpp
- src/tcop/tcop.cpp
- test/catalog/catalog_test.cpp
- test/concurrency/transaction_tests_util.cpp
- test/statistics/stats_tests_util.cpp
In this PR, error messages are propagated to the front end when 
* A query accesses a table/database which doesn't exist 
* It fails to parse the query 
* Query planner is unimplemented (e.g. join queries, select for update)
Now when accessing a table which doesn't exist, an exception will be thrown and possibly propagate up to the front end. Throwing an exception is slow, but this should not happen very often. 
End-to-end test cases are added to `PelotonTest.java`. 
However, it doesn't cover all the unimplemented features yet. It would take a while for me to figure out all features that are not implemented. **If you know some feature not supported off-hand and not covered by my code, please kindly leave a comment.** Thanks! 
@sid1607  Please review what I changed in the wire protocol …
> psql & jdbc error message 

- src/include/statistics/backend_stats_context.h
- src/statistics/backend_stats_context.cpp
Callgrind reports that stat cuckoomap constructor & destructor have high cost (even just called once). Removed it temporarily so that we can benchmark tpcc first.
> Disable stat cuckoomap initialization

- src/optimizer/simple_optimizer.cpp
After adding the error messages we will throw an exception when encountering an "select for update" statement, which prevents TPC-C from running successfully. I commented out that exception for now to allow us profiling the system first. Eventually we have to support that.
> Comment out the exception for "select for update".

- src/common/init.cpp
- src/include/storage/data_table.h
- src/storage/data_table.cpp
- test/executor/loader_test.cpp
- test/include/common/harness.h
- test/performance/insert_performance_test.cpp
for now, the number of preallocated group is set to the number of threads / 2.
> support scalable tile group allocation

- src/common/varlen_pool.cpp
- src/include/common/varlen_pool.h
This PR replaces mutex in varlen pool with spinlock and tries to reduce critical path protected by locks.
> replace mutex in varlen pool with spinlock

- src/common/portal.cpp
- src/include/common/portal.h
- src/include/planner/abstract_scan_plan.h
- src/include/planner/project_info.h
- src/include/planner/seq_scan_plan.h
- src/include/tcop/tcop.h
- src/networking/protocol.cpp
- src/planner/index_scan_plan.cpp
- src/planner/project_info.cpp
- src/planner/seq_scan_plan.cpp
- src/planner/update_plan.cpp
- src/tcop/tcop.cpp
The old binding mechanism was copying parameter values into predicates and changing plans in place. That was unclean software engineering and could introduce extra copies of parameters.
After this refactoring, Peloton is going to save parameters values in the per-connection cache, and pass that to the executor context for the evaluation in the execution.
**Note:** There're still two places where we're modifying the plan in-place right now: inserted tuples in the insert plan and index scan keys in in the index scan plan. We may also want to refactor those two places in the future.
> Refactor the binding mechanism

- src/include/storage/indirection_array.h
- src/include/wire/libevent_server.h
- src/storage/data_table.cpp
- src/wire/libevent_callbacks.cpp
- src/wire/libevent_socket.cpp
Profiled peloton's memory usage with `valgrind massif` and found a few memory issues in peloton:
* When @sid1607 and I were measuring tpcc performance last week, the stat mode was turned on by default, which doubles memory usage. This was fixed in PR #342. 
* The associated **indirection array** is not dropped when the table is destructed. In this PR, it's freed as soon as its table is dropped. 
* The **packet manager** keeps the per connection query statement & plan caches, but it's not cleaned up immediately after the connection is closed. This leads to references to un-freed **indexes** which takes lots of space. 
* A minor memory leak in libevent where event objects are new'ed but not freed.  
Another issue not directly related to memory is the use `lock_free_array` to store tile …
> Memory issues

- script/installation/fedora-setup.sh
I tried building Peloton on Fedora 24 and it built successfully. So I would like to provide my script for setting up necessary dependencies on Fedora 24 (64-bit).
> Add a setting up script for Fedora 24

- src/common/types.cpp
- src/common/value.cpp
- src/include/common/types.h
- src/include/expression/expression_util.h
- src/include/expression/tuple_value_expression.h
- src/optimizer/simple_optimizer.cpp
- src/planner/seq_scan_plan.cpp
- test/expression/expression_util_test.cpp
I want to get this in now before I start making major changes. Otherwise my code will die on a branch when I get tied up with other professor duties and can't get back to this. Oh yeah this was for #356
* Added back the `TypeIdToString()` and `StringToTypeId()` utility functions to 'types.h'. Clang-format then cleaned up a bunch of other code.
* Added `ExpressionUtil::GetInfo(`) for creating a string representation of an entire `AbstractExpression` tree (with a testcase, you dank mofo)
* Refactored `TupleValueExpression` so that its internal data members are private.
> Initial ExpressionUtil enhancements

- src/include/statistics/backend_stats_context.h
- src/statistics/backend_stats_context.cpp
There was a race condition when multiple threads initialize the metric for a new index. @malin1993ml
> Fix race condition in index metric initialization [#355]

- src/concurrency/timestamp_ordering_transaction_manager.cpp
- src/include/common/types.h
- src/include/concurrency/epoch_manager.h
- src/include/concurrency/timestamp_ordering_transaction_manager.h
- src/include/concurrency/transaction.h
- src/include/concurrency/transaction_manager.h
- test/concurrency/transaction_test.cpp
- test/include/concurrency/transaction_tests_util.h
Use the BeginReadOnlyTransaction() method to create a pre-declared read-only transaction.
Signed-off-by: Jiexi Lin <jxlin39@gmail.com>
> Add pre-declared read only support

- src/common/array_type.cpp
- src/common/boolean_type.cpp
- src/common/type.cpp
- src/common/value.cpp
- src/include/common/value.h
- src/include/common/value_factory.h
- src/include/expression/conjunction_expression.h
- src/include/expression/expression_util.h
- src/include/expression/operator_expression.h
- src/index/index.cpp
- test/common/array_value_test.cpp
- test/common/boolean_value_test.cpp
- test/executor/seq_scan_test.cpp
- test/optimizer/rule_test.cpp
This commit fixes a lot of the problems with the Boolean type:
1. We were not able to convert VARCHARs to BOOLEANs.
2. And then even if we could, we had mispelled 'true' and 'false' so it wouldn't have worked anyway.
3. `BooleanType::CompareEquals` would always return true if you compared a NULL value...
4. This was because it would call `ValueFactory::GetBooleanValue` which only supported bool inputs. That means `PELOTON_BOOLEAN_NULL` was always converted to true
5. And then because I was disappointed that our code coverage has not moved up in a few months, I busted out new boolean test cases to make sure that all of this is working properly.
Note that **clang-format** reformatted some of the the source code files when I edited them so that's why there are a bunch of changes...
> Fixes for Boolean Value Type

- script/installation/packages.sh
- src/common/config.cpp
- src/common/configuration.cpp
- src/common/types.cpp
- src/include/common/exception.h
- src/include/common/types.h
- src/include/common/value.h
- src/include/expression/expression_util.h
- src/include/logging/checkpoint_manager.h
- src/include/logging/log_manager.h
- src/include/logging/logging_util.h
- src/include/storage/data_table.h
- src/include/storage/storage_manager.h
- src/logging/backend_logger.cpp
- src/logging/frontend_logger.cpp
- src/logging/log_manager.cpp
- src/logging/logging_util.cpp
- src/main/logger/logger.cpp
- src/main/logger/logger_workload.cpp
- src/storage/storage_manager.cpp
- src/storage/tile_group_factory.cpp
- test/common/boolean_value_test.cpp
- test/common/types_test.cpp
- test/logging/logging_test.cpp
Our beloved 'types.h' file has become a dumping ground for whatever global value that people need. It's sad in some ways.
In this pull request, I moved stuff out that didn't belong there, fixed up some of the ToString/FromString functions, and made sure that everything falls under the 'peloton' namespace.
> Cleaning up types.h

- test/common/timestamp_value_test.cpp
- test/container/priority_queue_test.cpp
Basic tests to cover comparison functions and hash functions in timestamp_type.cpp, still working on tests for hashcombine and cast functions for timestamp_type.cpp. Extra tests that covers src/container/priority_queue.cpp.
> test for timestamp_type.cpp

- src/common/type.cpp
- src/common/value.cpp
- src/common/varlen_pool.cpp
- src/common/varlen_type.cpp
- src/executor/update_executor.cpp
- src/gc/gc_manager.cpp
- src/gc/transaction_level_gc_manager.cpp
- src/include/common/container_tuple.h
- src/include/common/type.h
- src/include/common/value.h
- src/include/common/varlen_pool.h
- src/include/common/varlen_type.h
- src/include/gc/gc_manager.h
- src/include/planner/project_info.h
- src/include/storage/tile.h
- src/include/storage/tile_group.h
- src/planner/project_info.cpp
- src/storage/tile.cpp
- src/storage/tile_group.cpp
- test/common/varlen_pool_test.cpp
In this PR, we implemented the following features:
- Support reference count in varlen pool. 
- Make the update executor aware of the reference count and perform a shallow copy on varlen column
- Make the GC manager aware of the reference count and reclaim memory in the varlen pool.
#396
> Support reference count in varlen type

- src/executor/index_scan_executor.cpp
- src/executor/plan_executor.cpp
- src/include/executor/plan_executor.h
- src/include/expression/expression_util.h
- src/include/planner/plan_util.h
- src/planner/abstract_plan.cpp
- src/tcop/tcop.cpp
- test/executor/create_index_test.cpp
- test/executor/delete_test.cpp
- test/executor/drop_test.cpp
- test/executor/update_test.cpp
- test/optimizer/simple_optimizer_test.cpp
- test/planner/planner_test.cpp
- test/sql/sql_tests_util.cpp
- test/statistics/stats_tests_util.cpp
This PR makes it so that we don't call the pretty-print function on the query plan *every* time we execute a query.
We never saw this because `PlanExecutor::Print()` was using `LOG_TRACE`. This is not a huge win but it does remove wasted cycles.
> Remove PlanExecutor::Print() and replace it with PlanUtil::GetInfo()

- src/executor/plan_executor.cpp
- src/include/executor/copy_executor.h
- src/include/executor/plan_executor.h
- src/include/tcop/tcop.h
- src/include/wire/libevent_server.h
- src/include/wire/libevent_thread.h
- src/include/wire/packet_manager.h
- src/networking/protocol.cpp
- src/tcop/tcop.cpp
- test/executor/copy_test.cpp
- test/executor/create_index_test.cpp
- test/executor/delete_test.cpp
- test/executor/update_test.cpp
- test/optimizer/simple_optimizer_test.cpp
- test/sql/sql_tests_util.cpp
- test/statistics/stats_test.cpp
- test/statistics/stats_tests_util.cpp
Features introduced by this PR include:
- Instantiation of tcop per client
- Adding state in tcop to track active tansactions for a given connection
- Support nested transactions by maintaining tcop state as stack
- Reuse same transaction object for all queries within the same BEGIN-COMMIT block
> #394: Added frontend txn handling bug fix

- src/catalog/catalog_util.cpp
- src/include/type/type.h
- src/include/type/value.h
- src/include/type/value_factory.h
- src/networking/protocol.cpp
- src/type/array_type.cpp
- src/type/bigint_type.cpp
- src/type/boolean_type.cpp
- src/type/decimal_type.cpp
- src/type/integer_parent_type.cpp
- src/type/integer_type.cpp
- src/type/smallint_type.cpp
- src/type/timestamp_type.cpp
- src/type/tinyint_type.cpp
- src/type/type.cpp
- src/type/value.cpp
- src/type/varlen_type.cpp
- test/common/array_value_test.cpp
- test/planner/planner_test.cpp
- test/storage/tuple_test.cpp
- test/storage/value_copy_test.cpp
In this PR, we:
- Replace all `CheckComparable()` and `CheckInteger()` with asserts
- Add a null flag to value type and simplify the `IsNull()`'s check
- Inline simple functions in type/value
- Support shallow copy in varlen type
#419
> Fix value/type system issues

- src/executor/copy_executor.cpp
- src/executor/logical_tile.cpp
- src/executor/plan_executor.cpp
- src/include/executor/logical_tile.h
- src/include/wire/packet_manager.h
- src/networking/protocol.cpp
- test/sql/aggregate_sql_test.cpp
During result tuple materialization, this PR materializes NULL values as 0B strings instead of 'integer_null', 'timestamp_null', etc. Then, protocol.cpp checks if the size of the value string is 0B. If it is, it treats it as a NULL value and handles it according to the wire protocol specifications.
OrderStatus doesn't give unexpected errors any more.
Further details in #415
> Handle NULL values with Frontend

- src/executor/index_scan_executor.cpp
From callgrind result on cmu-db/peloton/master (9f1c88f55e979a124a05ea44fc0420d7dd839cea), the problem is the varlen pool allocate. By tracing the code I find that [this line](https://github.com/cmu-db/peloton/blob/master/src/executor/index_scan_executor.cpp#L403) is allocating a temp varlen value for a tuple key from a per index varlen pool. It causes unnecessary contention over the index's varlen pool.
After switch to the executor context varlen pool, we get the performance back to normal level.
#426
> Fix varlen pool usage in secondary index scan

- script/oltpbenchmark/testbed/.gitignore
- script/oltpbenchmark/testbed/measure-performance-tpcc.py
- src/brain/index_tuner.cpp
- src/catalog/catalog.cpp
- src/catalog/schema.cpp
- src/include/catalog/column.h
- src/include/catalog/schema.h
- src/include/common/timer.h
- src/include/index/btree_index.h
- src/include/index/index_factory.h
- src/include/index/ints_key.h
- src/include/util/string_util.h
- src/index/btree_index.cpp
- src/index/bwtree_index.cpp
- src/index/index_factory.cpp
- src/main/tpcc/tpcc_loader.cpp
- src/main/ycsb/ycsb_loader.cpp
- src/tcop/tcop.cpp
- test/catalog/constraints_tests_util.cpp
- test/concurrency/transaction_tests_util.cpp
- test/executor/executor_tests_util.cpp
- test/executor/tile_group_layout_test.cpp
- test/index/hybrid_index_test.cpp
- test/index/index_intskey_test.cpp
- test/index/index_test.cpp
- test/index/index_util_test.cpp
- test/performance/index_performance_test.cpp
- test/util/string_util_test.cpp
This PR re-enables the specialized IntsKey comparators that were commented out for the indexes. I have not tested whether this is fully working but I added a basic test case.
I also fixed it so that we don't hardcode the name of **every** to be `CUSTOMER_PKEY` ☹
This is for #431
> Index IntsKey Fixes

- src/common/statement.cpp
- src/include/common/statement.h
- src/networking/protocol.cpp
Tcop uses the query type (i.e. the first word in the query string) to identify if the query is BEGIN, COMMIT or ROLLBACK to handle the transaction in the backend appropriately. Until now this was done using statement->SetQueryType(). However, the query type is not set while executing the simple query protocol (i.e. while interacting with psql). For this reason, these Transaction switches went unnoticed by tcop. This PR fixes this issue by setting query type on statement construction for the simple query protocol. #435
> Transaction Rollback Fix in psql

- src/executor/index_scan_executor.cpp
- src/include/executor/index_scan_executor.h
- src/include/planner/index_scan_plan.h
- src/index/index.cpp
- src/planner/index_scan_plan.cpp
- test/common/boolean_value_test.cpp
- test/common/timestamp_value_test.cpp
- test/executor/join_test.cpp
- test/index/hybrid_index_test.cpp
- test/sql/index_scan_sql_test.cpp
This PR adds the logic to handle left/right open range index scan in the IndexScanExecutor. Special flags will be set when constructing the IndexScanPlan in the optimizer, and then IndexScanExecutor will take the flags in the plan and perform pruning on the head/tail of the return tuple list if the flags indicate so.
We have to do that because the raw index can only return tuples for a close-boundary range. The logic was handled by index::Compare(), but that function will be removed soon by @wangziqi2013 .
@wangziqi2013 After you remove the index::Compare(), it seems to me that we no longer need IndexMetadata::GetTupleToIndexMapping and some related interfaces. Can you double check that and remove unnecessary code? I cannot remove them now since the compilation would fail when we still …
> Special case comparison on first/last tuple in index range scan

- script/oltpbenchmark/testbed/measure-performance-tpcc.py
- script/testing/jdbc/src/PelotonErrorTest.java
- script/testing/jdbc/test_jdbc.sh
- src/catalog/column.cpp
- src/catalog/constraint.cpp
- src/catalog/schema.cpp
- src/include/index/ints_key.h
- src/include/index/scan_optimizer.h
- src/include/storage/tile_group.h
- src/include/storage/tuple.h
- src/include/util/string_util.h
- src/index/btree_index.cpp
- src/index/bwtree_index.cpp
- src/index/index_factory.cpp
- src/storage/tile.cpp
- src/storage/tile_group.cpp
- src/storage/tuple.cpp
- test/index/index_intskey_test.cpp
- test/util/string_util_test.cpp
Lots of random stuff in here.
+ New JDBC test that can cause a txn to abort due to conflict. We don't run this automatically. I just wanted to understand how our server-side errors cause exceptions.
+ Inlining two simple methods.
+ Expanded `IndexIntsKeyTest` to look at all combination of integer types
+ New `StringUtil::Format()` helper method that works just like printf.
+ Cleaned up @wangziqi2013's new `CompactIntsKey`
+ Cleaned up `Tuple`
I'm pushing out this PR in memory of @jessesleeping for always being [dangerous](https://youtu.be/pJk0p-98Xzc) with the 9022 bat.
> IntsKey Tests + GetInfo() Clean-up + In-lining

- src/executor/index_scan_executor.cpp
- src/index/bwtree_index.cpp
- src/optimizer/simple_optimizer.cpp
All the key column ids for the index should be initiated even though the corresponding values are fake. The future optimizer should also be careful about this.
> Fix the issue caused by stock index scan plan

- src/include/catalog/schema.h
- src/include/index/generic_key.h
- src/include/type/type_util.h
- src/index/btree_index.cpp
- src/index/bwtree_index.cpp
- src/index/index_factory.cpp
- test/index/index_intskey_test.cpp
- test/index/index_test.cpp
- test/performance/index_performance_test.cpp
- test/type/type_util_test.cpp
- test/type/value_test.cpp
This PR is for the new `FastGenericKeyComparator`. This allows us to compare the values of `GenericKey` objects from their data pointers rather than having to create `Value` wrappers. This uses the new `TypeUtil::Compare*Raw()` methods from my previous PR (#446).
> FastGenericKeyComparator

- src/include/concurrency/epoch_manager.h
- src/include/type/types.h
This PR provides a fast fix for the GC problem in the current version of Peloton. In some cases, the current version of Peloton cannot guarantee that the number of started transactions equals to the number of ended transactions. That is, there exists certain transactions that never terminate. This causes the GC to suspend because the GC reclaims expired versions only if all the transactions in an expired epoch have been committed. The current fix is to timeout those outstanding transactions. 
Please note that a better solution must be made to fully address this problem.
> GC problem quick hacking

- src/brain/index_tuner.cpp
- src/brain/layout_tuner.cpp
- src/brain/sample.cpp
- src/catalog/catalog.cpp
- src/common/init.cpp
- src/common/statement.cpp
- src/configuration/configuration.cpp
- src/executor/index_scan_executor.cpp
- src/include/brain/brain_util.h
- src/include/brain/index_tuner.h
- src/include/brain/sample.h
- src/include/catalog/catalog.h
- src/include/common/statement.h
- src/include/configuration/configuration.h
- src/include/index/index.h
- src/include/parser/sql_statement.h
- src/include/planner/plan_util.h
- src/include/tcop/tcop.h
- src/include/wire/packet_manager.h
- src/index/index.cpp
- src/main/sdbench/sdbench_workload.cpp
- src/optimizer/simple_optimizer.cpp
- src/parser/sql_statement.cpp
- src/tcop/tcop.cpp
- src/wire/packet_manager.cpp
- test/brain/brain_util_test.cpp
- test/brain/index_tuner_test.cpp
- test/brain/layout_tuner_test.cpp
You can now tell a `PacketManager` that it needs to invalidate the cached query plan for all of its PreparedStatements and then replan them the next time that they are invoked. I am assuming that there is only one `PacketManager` per thread.
This code is nasty. I'm not pleaed with myself. But the `PacketManager` is a mess and there is no easy way to break out the PreparedStatement cache from it for now.
There is no easy way to write a test for this either because the `PacketManager` requires you to start up the libevent code. So I tested it manually (for now) but inserting this chunk of code into `IndexScanExecutor::DExecute()`
```
// HACK
LOG_DEBUG(
"HACK: Telling PacketManagers to invalidate the PreparedStatements for "
"'%s'",
table_->GetName().c_str());
for (auto pm : …
```
> Server-side PreparedStatement Invalidation

- src/gc/gc_manager.cpp
- src/gc/transaction_level_gc_manager.cpp
- src/include/gc/gc_manager.h
- src/include/storage/tile.h
- src/include/storage/tile_group.h
- src/include/type/ephemeral_pool.h
- src/include/type/type.h
- src/include/type/value.h
- src/include/type/varlen_type.h
- src/type/type.cpp
- src/type/varlen_type.cpp
1. Bring back the logic in GCManager to reclaim varlen pool
2. Tweek the varlen pool implementation to support `Free()`
#442
> Fix memory leak in varlen pool

- src/brain/index_tuner.cpp
- src/include/brain/brain_util.h
- src/include/brain/index_tuner.h
- test/brain/brain_util_test.cpp
I couldn't get the file to work building the indexes as it was It improves performance some, but
does not choose all the correct indices. I think this is because the "weight" is not correct in the file that @apavlo gave me.
The following file gives the correct indices.
[samples.txt](https://github.com/cmu-db/peloton/files/691872/samples.txt)
> Read stats from file

- src/include/planner/abstract_scan_plan.h
- test/concurrency/select_for_update_txn_test.cpp
There is some bug with the current select_for_update logic that it sometime fails detecting write-write conflict. We just disable it for now and will fix it later.
Thanks @MattPerron for pointing out this bug.
#484
> Disable select_for_update

- src/executor/order_by_executor.cpp
- src/optimizer/simple_optimizer.cpp
- test/sql/order_by_queries_sql_test.cpp
This PR resolves issue #385.
InSimpleOptimizer: Adding the order by column explicitely into the column map, to allow materialization and sorting.
In OrderByExecutor: Use only the columns in select for output_schema.
As requested, with unit tests.
> OrderBy Partial Fix Bug #385 and unit tests

- src/executor/abstract_executor.cpp
- src/executor/hybrid_scan_executor.cpp
- src/executor/index_scan_executor.cpp
- src/executor/order_by_executor.cpp
- src/include/executor/abstract_executor.h
- src/include/executor/order_by_executor.h
- src/include/optimizer/simple_optimizer.h
- src/include/planner/order_by_plan.h
- src/index/bwtree_index.cpp
- src/networking/peloton_service.cpp
- src/optimizer/simple_optimizer.cpp
- src/tcop/tcop.cpp
- test/include/sql/sql_tests_util.h
- test/sql/order_by_sql_test.cpp
- test/sql/sql_tests_util.cpp
This PR includes the optimization for order_by and limit. When the underlying plan has the same ordering with the order_by expression, order_by executor doesn't perform sort operation. Order_by executor also utilizes the limit number and offset to decrease invoking the underlying executor. Performance test has been done. It is ~1620 txns/sec on my local desk top. After the rebase with master, the throughput is ~1540 txns/sec.
> Orderby/Limit Optimization

- src/executor/hash_executor.cpp
- src/executor/logical_tile.cpp
- src/optimizer/simple_optimizer.cpp
- test/sql/distinct_sql_test.cpp
This PR adds partial support for `SELECT DISTINCT` queries. There are two scenarios not covered currently.
- <s>`SELECT DISTINCT *` was not implemented due to an assert on the `hash_executor`, but it is a simple fix. </s>
- `DISTINCT` aggregations go through another flow, I suggest opening another issue for it.
EDIT: This PR now supports `SELECT DISTINCT *` queries.
> Add support for DISTINCT (#444)

- src/include/type/timestamp_type.h
- src/include/type/varlen_type.h
- src/optimizer/simple_optimizer.cpp
- src/type/timestamp_type.cpp
- src/type/varlen_type.cpp
- test/sql/aggregate_sql_test.cpp
This change Fixes Min/Max aggregations for Timestamps by adding the missing methods.
It is not a total fix for issue #382 because the system still crashes for VARCHAR Min/Max aggregations.
In addition I uncommented the SQL tests for Min/Max aggregations on Timestamps.
Now focusing on varchar.
> Fix Min/Max aggregations for Timestamps. Issue #382

- src/include/optimizer/simple_optimizer.h
- src/optimizer/simple_optimizer.cpp
- test/sql/order_by_sql_test.cpp
This PR solves Bug #517
The bug was caused by the order of operations in SimpleOptimizer, since ProjectPlan was always placed below OrderByPlan in the plan tree, the OrderByPlan would order only the output.
The solution was to check if there was an order_by before creating the ProjectPlan, and take care to not recreate it in a later point. This required moving the logic of order_by and order_by limit to separate functions.
The previous PR review is also addressed in this.
> Bugfix #517

- src/optimizer/simple_optimizer.cpp
- test/sql/update_sql_test.cpp
This PR solves bug #380 
The bug was caused by an incompatibility between the table attribute type and the update value type. The update value must be reinterpreted as the table attribute to allow correct input.
> Interpret correctly update values

- src/parser/sql_parser.y
- src/parser/sql_scanner.l
These are minor bug fixes for #518 and a unreported issue: If somebody explicitly sets 'USING BWTREE' or 'USING HASH' while creating an index, a segmentation fault occurs.  The cause of the this issue is an illegal type cast in handling an unsigned integer value.
> Minor bug fixes in SQL parser

- src/executor/plan_executor.cpp
- src/executor/populate_index_executor.cpp
- src/executor/seq_scan_executor.cpp
- src/include/executor/executors.h
- src/include/executor/populate_index_executor.h
- src/include/executor/seq_scan_executor.h
- src/include/planner/plan_util.h
- src/include/planner/populate_index_plan.h
- src/include/type/types.h
- src/optimizer/simple_optimizer.cpp
- src/planner/populate_index_plan.cpp
- src/type/types.cpp
- test/sql/index_scan_sql_test.cpp
This PR fixes big #529.
As suggested, a `PopulateIndexExecutor` that consumes the output of a `SeqScanExecutor` was created.
I accept suggestions on how to refactor the conditions on `SeqScanExecutor`.
> Creates populate index planner/executor

- src/include/parser/delete_statement.h
- src/include/parser/parsenodes.h
- src/include/parser/parser_utils.h
- src/include/parser/postgresparser.h
- src/parser/parser_utils.cpp
- src/parser/postgresparser.cpp
- src/parser/sql_statement.cpp
- test/parser/postgresparser_test.cpp
Delete support is added for the new PostgreSQL parser.
table_info_ is added in DeleteStatement temporarily to make the old parser be compiled.
> Delete for the new parser

- src/include/expression/abstract_expression.h
- src/include/parser/parsenodes.h
- src/include/parser/postgresparser.h
- src/parser/postgresparser.cpp
- test/parser/postgresparser_test.cpp
This PR supports update statement for the new parser. The newly added test cases depends on PR #581 to test OperatorExpression in the SET caluse.
> Update for the new parser

- src/include/parser/insert_statement.h
- src/include/parser/parsenodes.h
- src/include/parser/postgresparser.h
- src/parser/postgresparser.cpp
- test/parser/parser_test.cpp
- test/parser/postgresparser_test.cpp
- test/sql/order_by_sql_test.cpp
Three different types of INSERT statements are all supported:
(1) INSERT INTO foo VALUES (1, 2, 3);
(2) INSERT INTO foo VALUES (1, 2, 3), (4, 5, 6);
(3) INSERT INTO foo select * from bar where id = 5;
table_info_ is added in InsertStatement temporarily to make the old parser be compiled.
> Support Insert statement for the new parser

- src/include/parser/create_statement.h
- src/include/parser/parsenodes.h
- src/include/parser/postgresparser.h
- src/parser/postgresparser.cpp
- test/parser/postgresparser_test.cpp
This PR adds support for transform of simple CREATE statements such as
"CREATE TABLE Persons (PersonID int, LastName varchar(255));"
and fixed some bug in the destructor of Peloton CreateStatement class.
> support for simple CREATE statements

- src/planner/insert_plan.cpp
- test/planner/planner_test.cpp
Looks like there is a mistake in building parameter_vector_ for insert plan in case insert statement contains column list and value list with constants and parameters. This case wasn't covered by test so I added one.
> [FIX] proper parameter indexing in insert plans

- src/include/type/value_factory.h
- src/tcop/tcop.cpp
- src/type/boolean_type.cpp
- src/type/value.cpp
* TrafficCop now supports boolean types
* We now correctly cast VARCAR to booleans for comparisons.
This fixes #596
> Fixes for BOOLEAN

- src/include/type/type_util.h
- src/include/type/types.h
- src/tcop/tcop.cpp
- src/type/bigint_type.cpp
- src/type/decimal_type.cpp
- src/type/integer_type.cpp
- src/type/smallint_type.cpp
- src/type/tinyint_type.cpp
- src/type/value.cpp
- src/type/varlen_type.cpp
- test/sql/update_sql_test.cpp
- test/type/boolean_value_test.cpp
- test/type/numeric_value_test.cpp
This is the same as #602. It got closed when I did a push force.
http://i.imgur.com/sMOVCZt.gifv
This adds support to cast strings to the appropriate numeric type in any expression. One of the big changes is that I also converted the comparison and modification operations in each of the types into C macros. It's cleaner code now but I think that this will all go away when @pmenon's engine shows up...
```
postgres=# CREATE TABLE foo (val0 TINYINT, val1 SMALLINT, val2 INTEGER, val3 BIGINT);
CREATE TABLE foo (val0 TINYINT, val1 SMALLINT, val2 INTEGER, va
postgres=# INSERT INTO foo VALUES (1, 22, 333, 4444);
INSERT INTO foo VALUES (1, 22, 333, 4444) 1
postgres=# INSERT INTO foo VALUES (2, 33, 444, 5555);
INSERT INTO foo VALUES (2, 33, 444, 5555) 1
postgres=# SELECT * FROM foo WHERE val1 >= …
```
> Add support for casting VARCHAR to any numeric type

- src/executor/plan_executor.cpp
- src/include/executor/plan_executor.h
- src/include/storage/database.h
- src/include/tcop/tcop.h
- src/networking/peloton_service.cpp
- src/tcop/tcop.cpp
- test/executor/copy_test.cpp
- test/executor/create_index_test.cpp
- test/executor/delete_test.cpp
- test/executor/update_test.cpp
- test/optimizer/optimizer_test.cpp
- test/optimizer/simple_optimizer_test.cpp
- test/statistics/stats_test.cpp
1. Renamed `peloton_status` to `ExecuteStatus`
2. Renamed `bridge` namespace to `executor`
> Fixing names

- src/include/expression/expression_util.h
- src/include/parser/create_statement.h
- src/include/parser/postgresparser.h
- src/include/type/value.h
- src/include/util/string_util.h
- src/parser/postgresparser.cpp
- src/planner/insert_plan.cpp
- src/util/string_util.cpp
- test/parser/postgresparser_test.cpp
This PR contains several fixes and adds support for several features in the parser according to the open issues:
- Support DEFAULT, REFERENCE and CHECK constraints in CREATE TABLE  (#631, #625 )
- Fix assertion failure in insert executor (#631, #578)
- Make TEXT type an alias to VARCHAR(1000000000) (#626)
Now Peloton can support the following CREATE TABLE statement in the parser:
``` sql
CREATE TABLE TEST (
a int DEFAULT 1+2,
b int REFERENCES table2 (bb) ON UPDATE CASCADE,
c varchar(32) REFERENCES table3 (cc) MATCH FULL ON DELETE SET NULL,
d int CHECK (d+1 > 0),
e TEXT
);
```
- Support parsing FunctionExpression `SELECT add(1,a) FROM TEST WHERE FUN(b) > 2`
**_For the constraint team_**  (@vittvolt, @xinzhang1234, +1):
Some members are added in the create_statement.h to store the parsing …
> Parser Fix

- .travis.yml
- CMakeLists.txt
- cmake/Dependencies.cmake
- src/include/parser/copy_statement.h
- src/include/parser/create_statement.h
- src/include/parser/delete_statement.h
- src/include/parser/drop_statement.h
- src/include/parser/execute_statement.h
- src/include/parser/insert_statement.h
- src/include/parser/prepare_statement.h
- src/include/parser/select_statement.h
- src/include/parser/sql_statement.h
- src/include/parser/update_statement.h
- src/include/type/byte_array.h
- test/CMakeLists.txt
- test/gc/transaction_level_gc_manager_test.cpp
- test/planner/planner_test.cpp
- third_party/libcuckoo/cuckoohash_map.hh
- third_party/libpg_query/src/postgres/src_backend_utils_mmgr_mcxt.c
This PR replaces Valgrind with `-fsanitize` flags. Valgrind took more than an hour to run all the tests whereas the test suite runs under 10mins with the sanitization flags.
Sanitization flags are enabled through the `USE_SANITIZER` cmake option. We currently support three sanitizers: Address, Thread, and Undefined. Address sanitization ([ASan](https://clang.llvm.org/docs/AddressSanitizer.html)) detects various memory-related problems. Thread sanitization ([TSan](https://clang.llvm.org/docs/ThreadSanitizer.html)) detects data races. Undefined behavior sanitization ([UBSan](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html)) detects misaligned pointer usage, overflows etc.
This isn't ready to be merged, but feedback is welcome.
> Use `-fsanitize` flags for build

- src/include/parser/postgresparser.h
- src/parser/postgresparser.cpp
- test/parser/postgresparser_test.cpp
This PR adds the missing part for parsing constant DEFAULT constraint #644 and refactor postgresparser by adding ExprTransform for all expression nodes for better modularity.
> Minor fix for DEFAULT constraint and refactor postgresparser

- script/installation/packages.sh
Running packages install via packages.sh seem to fail due to apt-get errors. 
I am running peloton via vagrant setup provided on the installation page. 
Os version: Mac OS X 10.12.5.
This PR fixes it and I am able to build and install peloton successfully after this.
Thanks,
Arun
> fix apt-get install errors on ubuntu when run via vagrant on OSX

- src/planner/insert_plan.cpp
This PR fixes the TPC-C bug mentioned in #665 by specifying the parameter offset correctly to bind the values. Now the TPC-C benchmark can be run successfully.
> Fix TPC-C failure

- src/common/statement.cpp
- src/include/common/statement.h
- src/include/type/types.h
- src/include/wire/packet_manager.h
- src/tcop/tcop.cpp
- src/wire/packet_manager.cpp
1. The query_type is still of string type. Convert it to upper case to match the keywords('BEGIN',  'END', 'ROLLBACK') 
2. Originally the query_type was generated by splitting the query_string using blank characters.(https://github.com/cmu-db/peloton/blob/master/src/common/statement.cpp#L31) A special case is that when the query is 'BEGIN;', it takes query_type as 'BEGIN;' instead of 'BEGIN'. In this case, remove the ending semi-colon.
> keyword case insensitive issue

- src/include/storage/tile_group.h
- src/storage/tile_group.cpp
This fixes the function name mangling in #715, which is also partially also mentioned in #705.  This issue seems to occur on some GCC versions, but it can be reproducible on dev1(5.4.0-6ubuntu1, 16.04.4), dev2(4.8.4-2ubuntu1, 14.04.3) and dev3(4.8.4-2ubuntu1, 14.04.3).
> Fix the name-mangling issue on release mode

- src/optimizer/operator_to_plan_transformer.cpp
- src/optimizer/optimizer.cpp
- src/optimizer/property_set.cpp
- test/sql/optimizer_sql_test.cpp
This PR fixes two bugs in the new optimizer:
1. #705. When mixing join predicates with single table predicates in hash join plan, the column in the single table predicate is absent during the predicate evaluation. This bug is fixed by ensuring the output column requirement for the hash join operator contains columns in the single table predicates. Note that predicate push-down has not been supported yet.
2.  #600. We enable the new optimizer to use index scan when the columns occurred in the predicates (only consider CompareEqualExpression) forms a subset of the index columns. But the new optimizer excludes the predicates that contain the index columns in the index scan plan, which leads to incorrect results for some queries.
> Fix hash join and index scan issues in the new optimizer

- src/include/common/exception.h
- src/planner/create_plan.cpp
- src/storage/tuple.cpp
- test/statistics/stats_test.cpp
- test/statistics/testing_stats_util.cpp
- test/storage/tuple_test.cpp
fix the bug #636. I add a check in planner phase. When generating a InsertPlan,  one should call tuple->SetValue for each element to be inserted. So I add the check in Tuple::SetValue.
> check the length before inserting data into VARCHAR or VARBINARY columns

- src/include/parser/postgresparser.h
- src/optimizer/stats/cost.cpp
- src/optimizer/stats/selectivity.cpp
- src/optimizer/stats/stats_storage.cpp
- src/optimizer/stats/tuple_samples_storage.cpp
- src/parser/postgresparser.cpp
- src/tcop/tcop.cpp
- test/parser/parser_test.cpp
This PR intents to fix issue #680 that peloton would crash with statements like "SELECT *" and "SELECT;"
The reason is that the Postgres parser does not think the statements mentioned above as wrong statements and the binder and optimizer would continue to execute the wrong parse tree and eventually crash.
The solution is to explicitly check that
1. The target list is not null, which can overcome "SELECT;" 
2. The from clause list is not null **when the target contains any variables 'like * or item column'**, this would overcome "SELECT *;"
A unit test case is added in parser_test to check "SELECT *" and "SELECT;".
There may still be other edge cases in 2 since right now only constant, bool expression and expression type are checked.
> Implement parser edge case

- cmake/Modules/CoverallsGenerateGcov.cmake
By default, `gcov` analyzes **all** included header files, including STL, boost, and LLVM headers. This is overkill. Moreover, it's been blowing up our builds because the log file size grows beyond 4MB.
This PR adds a flag to exclude library headers when performing code coverage.
> Remove STL headers from coverage

- src/include/wire/libevent_server.h
- src/include/wire/libevent_thread.h
- src/main/peloton/peloton.cpp
- src/wire/libevent_server.cpp
- src/wire/libevent_thread.cpp
This PR is a quick fix for preventing a crash happening when Peloton is run with the port which is occupied with some other process.  The fix will let the worker threads start to run _after_ checking all the network ports are available.
> Fix for graceful shutdown when Peloton's port binding fails

- src/codegen/query_compiler.cpp
- src/include/planner/abstract_plan.h
This PR fixes #777.  Currently, we do not check each target expression in non-trivial projections for codegen support. We perform the check in this PR.
> Check projection expressions for compilation support

- src/catalog/abstract_catalog.cpp
- src/include/planner/delete_plan.h
- src/include/planner/update_plan.h
- src/main/tpcc/tpcc_delivery.cpp
- src/optimizer/operator_to_plan_transformer.cpp
- src/planner/delete_plan.cpp
- src/planner/update_plan.cpp
- test/codegen/delete_translator_test.cpp
- test/concurrency/testing_transaction_util.cpp
- test/executor/mutate_test.cpp
- test/planner/planner_test.cpp
This quick PR removes the redundant code in the Update/Delete plans.   
`DeletePlan`'s constructor now only accepts the target table object, and nothing else.  The predicate/truncate information will be obtained from its child `SeqScanPlan`(or `IndexScanPlan` in the future). `UpdatePlan` also has only one constructor, from now on, which receives the target table and ProjectInfo objects. All the related code has also been fixed, such as optimizer, tests, etc.
I separated these from the codegen PR, for a review, and other planners such as `InsertPlan` will also have to be cleaned up.
> Tidy Up Delete/Update Planner

- src/brain/index_tuner.cpp
- src/codegen/buffering_consumer.cpp
- src/executor/aggregate_executor.cpp
- src/executor/aggregator.cpp
- src/executor/hash_join_executor.cpp
- src/executor/hybrid_scan_executor.cpp
- src/executor/index_scan_executor.cpp
- src/executor/insert_executor.cpp
- src/executor/merge_join_executor.cpp
- src/executor/nested_loop_join_executor.cpp
- src/executor/populate_index_executor.cpp
- src/executor/projection_executor.cpp
- src/executor/seq_scan_executor.cpp
- src/executor/update_executor.cpp
- src/gc/transaction_level_gc_manager.cpp
- src/include/codegen/buffering_consumer.h
- src/include/common/container_tuple.h
- src/include/executor/aggregator.h
- src/include/executor/hash_executor.h
- src/include/executor/hash_set_op_executor.h
- src/main/tpcc/tpcc_workload.cpp
- src/main/ycsb/ycsb_workload.cpp
- test/common/container_tuple_test.cpp
- test/executor/join_test.cpp
ContainerTuple is in src/common, but was still under namespace expression.  This PR removes namespace expression from ContainerTuple, for the sake of clarification and also of reading the code more effectively.
This is simple and straightforward, so it can be merged after the build passes.
> Remove namespace 'expression' from ContainerTuple 

- src/catalog/catalog.cpp
- src/catalog/column_catalog.cpp
- src/catalog/column_stats_catalog.cpp
- src/catalog/database_catalog.cpp
- src/catalog/database_metrics_catalog.cpp
- src/catalog/index_catalog.cpp
- src/catalog/index_metrics_catalog.cpp
- src/catalog/query_metrics_catalog.cpp
- src/catalog/table_catalog.cpp
- src/catalog/table_metrics_catalog.cpp
- src/optimizer/stats/stats_storage.cpp
- src/optimizer/stats/tuple_samples_storage.cpp
- src/storage/storage_manager.cpp
I just noticed that a few parts of the system use overly complicated singleton instantiations. This PR cleans it up using simple and safe C++11 constructs. No functional changes.
Note: I'm not a huge fan of singletons. In fact, most of these singletons aren't needed if we have an overarching "Peloton" object (or something like that) that can guarantee one-time initialization of the various catalog tables. Then these catalog classes can be regular non-singleton class that provide transactional access to the underlying catalog tables.
> Simplifiy singletons

- src/include/catalog/settings_catalog.h
- src/main/peloton/peloton.cpp
- src/settings/README.md
- src/settings/settings.cpp
- src/settings/settings_manager.cpp
After the settings PR, the `-display_settings` configuration parameter wasn't printing the configuration nicely on startup. This PR fixes it, cleaned up the settings README, and ran the code formatter. No functional changes.
> Pretty print configuration

- src/parser/postgresparser.cpp
- test/parser/parser_test.cpp
This is the fix for issue #808 and it contains:
- Change the parser to throw ParserException when faced with a syntax error
- Formatted old code
- Added an extra test query with invalid syntax in parser_test.cpp
> Handling syntax error in queries

- src/executor/hash_join_executor.cpp
- src/include/common/container_tuple.h
- test/executor/join_test.cpp
The hash_join_executor in the interpreted engine has been broken for a while. This PR fixes several issues related to the correctness problem:
- Use correct left column ids derived from the left hash keys in the hash_join_plan to probe the hash table
- Modify the comparator for ContainerTuple to make sure that the probe check is correct
- Support predicate evaluation in the executor
Since I have never touched the codes for ContainerTuple before, I need someone to help review this PR.
This PR is the first step to fix #807, the next step is to support predicate push-down so that the memory consumption can be reduced significantly. I will send another PR soon.
> Fix hash_join_executor in the interpreted engine

- src/catalog/index_catalog.cpp
- src/executor/hash_join_executor.cpp
- src/include/type/boolean_type.h
- src/include/type/limits.h
- src/include/type/timestamp_type.h
- src/include/type/types.h
- src/include/type/value.h
- src/include/type/value_factory.h
- src/optimizer/child_property_generator.cpp
- src/type/boolean_type.cpp
- src/type/date_type.cpp
- src/type/timestamp_type.cpp
- src/type/type.cpp
- src/type/types.cpp
- src/type/value.cpp
- src/type/varlen_type.cpp
- test/sql/insert_sql_test.cpp
- test/sql/typelimit_sql_test.cpp
- test/type/date_value_test.cpp
- test/type/type_test.cpp
- test/type/type_util_test.cpp
- test/type/types_test.cpp
- test/type/value_factory_test.cpp
- test/type/value_test.cpp
The `DATE` type was originally set to be uint32_t. The problem with this is that we had set `PELOTON_DATE_MIN` to be the same as `PELOTON_DATE_NULL`, which means that you could never have null dates.
This PR switches the `DATE` to be a int32_t. I also added new tests because the coverage for this code was nearly zero.
It also includes SQL tests that check whether we check that you can't insert the min values for types and end up with nulls.
I also fixed Value::Min/Max for some types.
https://www.youtube.com/watch?v=1XV-dWStHOI
> Switch DATE type to be int32

- src/concurrency/timestamp_ordering_transaction_manager.cpp
- src/executor/delete_executor.cpp
- src/executor/plan_executor.cpp
- src/include/optimizer/stats/hyperloglog.h
- src/network/service/peloton_service.cpp
- src/optimizer/stats/tuple_sampler.cpp
- src/planner/create_plan.cpp
- src/planner/insert_plan.cpp
- src/statistics/stats_aggregator.cpp
Fixes https://github.com/cmu-db/peloton/issues/869
uint64_t variables are resolved to **unsigned long long** on OS X and **unsigned long int** on linux. Log lines with uint64_t variables can be made portable with PRId64 macro.
Also fixes other minor bugs in trace level logs.
> Fix for building at trace log level

- src/include/planner/insert_plan.h
- src/planner/insert_plan.cpp
- test/catalog/manager_test.cpp
- test/catalog/tuple_schema_test.cpp
- test/codegen/insert_translator_test.cpp
- test/executor/create_test.cpp
- test/executor/join_test.cpp
- test/executor/logical_tile_test.cpp
- test/executor/mutate_test.cpp
- test/expression/expression_util_test.cpp
- test/include/index/testing_index_util.h
- test/index/index_intskey_test.cpp
- test/index/index_util_test.cpp
- test/index/testing_index_util.cpp
- test/optimizer/operator_test.cpp
- test/parser/parser_test.cpp
- test/parser/parser_utils_test.cpp
- test/parser/postgresparser_test.cpp
- test/planner/planner_test.cpp
- test/storage/data_table_test.cpp
- test/storage/masked_tuple_test.cpp
- test/storage/temp_table_test.cpp
- test/storage/tile_group_test.cpp
- test/storage/tile_test.cpp
- test/storage/tuple_test.cpp
- test/trigger/trigger_test.cpp
- test/type/array_value_test.cpp
- test/type/pool_test.cpp
- test/type/type_util_test.cpp
This PR removes all the `delete` calls in our `test` directory by applying smart pointers.   This work started by simplifying the `InsertPlan` code to enhance parameterizaton later in this week, so it would be nice to merge it soon.
The code changes are straightforward, so someone could spend less than quarter an hour to review them.
> Remove all delete calls in /test

- src/common/init.cpp
- src/include/threadpool/mono_queue_pool.h
- src/include/threadpool/worker_pool.h
- src/threadpool/worker.cpp
- src/threadpool/worker_pool.cpp
This PR reduces the CPU spikes from polling the task queue, and start up the thread pool at the beginning of the initialization stage of the peloton execution.  More discussions have been done in the mailing list and handling threads in peloton may have to be revisited further in near future. 
In addition, checking up the startup status and starting up the worker threads at submitting a new task is inevitable at this moment, because all the test cases were written in the way that this task pool had never existed and including startup() calls in all the test cases is a pain.
> Reduce CPU spikes from the thread pool

- src/include/network/protocol_handler.h
- src/network/network_connection.cpp
- src/network/postgres_protocol_handler.cpp
- src/network/protocol_handler.cpp
- test/network/select_all_test.cpp
It's the same PR as #908 
Fix for #878
The issue is due to that the server does not flush out all the packets. The client does not get the complete result so it looks like hanging.
The server should flush out all the packets before resetting the force_flush flag.
Previous PR doesn't run the check. Just to check if it can run check after changing the source repository.
> Fix for 'select * ' hanging

- src/catalog/catalog.cpp
- src/codegen/proxy/string_functions_proxy.cpp
- src/codegen/type/varchar_type.cpp
- src/function/string_functions.cpp
- src/include/codegen/proxy/string_functions_proxy.h
- src/include/function/string_functions.h
- src/include/type/types.h
- test/function/string_functions_test.cpp
- test/sql/string_functions_sql_test.cpp
- test/sql/stringfunctions_sql_test.cpp
In this PR we implement `Length` SQL function for the LLVM engine. Now we can support queries like `SELECT length(a) FROM table`. We also add a test case in `string_functions_test.cpp`.
> Implement function Length

- .clang-format
- src/binder/bind_node_visitor.cpp
- src/catalog/catalog.cpp
- src/codegen/proxy/timestamp_functions_proxy.cpp
- src/codegen/type/integer_type.cpp
- src/codegen/type/timestamp_type.cpp
- src/codegen/type/varchar_type.cpp
- src/function/date_functions.cpp
- src/function/functions.cpp
- src/function/timestamp_functions.cpp
- src/include/codegen/proxy/timestamp_functions_proxy.h
- src/include/function/functions.h
- src/include/function/timestamp_functions.h
- src/include/type/types.h
- src/type/types.cpp
- src/type/value.cpp
- test/function/timestamp_functions_test.cpp
- test/sql/timestamp_functions_sql_test.cpp
This PR implements the date_trunc SQL function. ~~It contains a SQL test, however I cannot do the real appropriate SQL test without adding the logic in the binder to check the DatePartType of the date_trunc function and replace the type string with its real type ID. That requires some fixes in #886.~~
> Add date_trunc function

- src/codegen/operator/update_translator.cpp
- src/codegen/table_storage.cpp
- test/codegen/update_translator_test.cpp
- test/sql/update_sql_test.cpp
This PR fixes #933 by casting to the value types that are defined in the schema of the table, before creating a storage space in `codegen`.  Previously this casting was missing, and #933 occurs.
Test cases are created exactly same as #933 case and added.
> Fix Issue 933 - Updating with mismatched types

- src/codegen/expression/comparison_translator.cpp
- src/codegen/expression/function_translator.cpp
- src/codegen/operator/insert_translator.cpp
- src/codegen/table_storage.cpp
- src/codegen/tuple_runtime.cpp
- src/codegen/type/bigint_type.cpp
- src/codegen/type/boolean_type.cpp
- src/codegen/type/date_type.cpp
- src/codegen/type/decimal_type.cpp
- src/codegen/type/integer_type.cpp
- src/codegen/type/smallint_type.cpp
- src/codegen/type/timestamp_type.cpp
- src/codegen/type/tinyint_type.cpp
- src/codegen/type/type_system.cpp
- src/codegen/type/varbinary_type.cpp
- src/codegen/type/varchar_type.cpp
- src/codegen/value.cpp
- src/include/codegen/type/type_system.h
- src/include/type/types.h
- src/type/types.cpp
- test/sql/projection_sql_test.cpp
- test/sql/type_sql_test.cpp
**Problem**: Right now, all the operators/functions in codegen assume non-null inputs, and rely on the `codegen::Value` class to wrap operators in "null-aware" wrappers to handle NULL inputs. This was okay as long as all calls go through `codegen::Value`. But, with the introduction of function expressions, this is no longer the case as these expressions directly call into the type system. Exposing the null logic externally is a bad idea; moreover, the functions themselves know how to handle NULLs.
**Solution**: Provide base classes that perform the same NULL-handling logic, deferring to derived classes to perform non-null-aware logic. This encapsulates NULL logic to the operator, which makes a lot more sense.
**Details**: In this PR, we introduce four base classes for casting, comparison, …
> Simplify NULL handling in type system

- src/codegen/compilation_context.cpp
- src/codegen/operator/delete_translator.cpp
- src/codegen/operator/insert_translator.cpp
- src/codegen/operator/operator_translator.cpp
- src/codegen/operator/table_scan_translator.cpp
- src/codegen/operator/update_translator.cpp
- src/codegen/proxy/storage_manager_proxy.cpp
- src/codegen/query.cpp
- src/include/codegen/compilation_context.h
- src/include/codegen/operator/operator_translator.h
- src/include/codegen/proxy/storage_manager_proxy.h
- src/include/codegen/query.h
This PR is a part of the clean-up's, and modifies `catalog` to `storage_manager` in codegen, which is more correct of naming.
> [Cleanup] Catalog -> StorageManager in Codegen

- src/include/common/container_tuple.h
- test/common/container_tuple_test.cpp
`ContainerTuple` has a `GetInfo()` method that wasn't implemented. This PR implements it as part of the December 2017 code cleanup.
> Fix ContainerTuple::GetInfo() to actually print out tuple

- test/codegen/bloom_filter_test.cpp
This PR fixes issue #964 
`std::make_unique` is a part of c++14 so using `std::unique_ptr` instead.
> Remove make_unique from bloom_filter_test.cpp

- script/validators/source_validator.py
As requested in #491:
* checks if source and header files define namespaces consistent to the directory they live in
* e.g. `/src/util/stringbox_util.cpp` has to define its functions in pelton::util
* e.g. `/src/include/codegen/operator/order_by_translator.h` has to define its functions in pelton::codegen::operator
* removes early return on failures in the validator script to create a list with all violations instead of just the first violation
The current code base violates this rule many times, refactoring is necessary. The validator script is also ran in the pre-commit hook, but there only staged files are checked, so it shouldn't cause problems. 
**Edit:** I realized that the validator script also runs in travis. To be able to pass the checks on this PR, I disabled the namespace …
> Add namespace check to validator script

- src/parser/postgresparser.cpp
This PR includes the fix for memory leak issues when transformation of a CREATE statement throws an exception.
> Fix for memory leak in failed CREATE transform

- src/gc/transaction_level_gc_manager.cpp
- src/include/gc/transaction_level_gc_manager.h
This adds the call to ClearGarbage function back to the Garbage Collector. It turns out that the Garbage Collector already has a StopGC function that will be called when Peloton shuts down. So I just added the call there.
> [Clean-Up] Add the ClearGarbage back to StopGC.

- src/codegen/type/decimal_type.cpp
Looks like the return type of the floor function as set incorrectly. This PR fixes it.
@saatviks Since this was your function, you can review the fix :)
> Fix return type for floor

- src/include/parser/create_statement.h
- src/include/parser/parsenodes.h
- src/include/parser/postgresparser.h
- src/include/type/value_factory.h
- src/parser/postgresparser.cpp
- src/type/varlen_type.cpp
- test/parser/parser_test.cpp
- test/parser/postgresparser_test.cpp
This PR adds support for DATE type and transform for TypeCast parsenodes. (Related issues: #909 #852) 
- Added the DATE type to corresponding places.
- Added the transform for TypeCast in Postgres: For type casts, the final cast results will be added to the parse tree (e.g. ' "2017-12-31"::DATE ' will be a single DATE type constant value expression after the transform)
- Added a cast from VARCHAR to DATE type with the default format for date strings: "YYYY-MM-DD".
- Provided an additional fix for handling memory leak in InsertTransform when faced with exceptions.
- Added additional helper functions to transform type names to DataType classes and type::typeId classes.
> Add support for DATE type and TypeCast Transform

- src/include/storage/table_factory.h
- src/storage/table_factory.cpp
- test/executor/tile_group_layout_test.cpp
This fixes the Tile Group Layout Test.
In the tile group layout test we were missing a parameter in the GetDataTable() function call because of which the next parameter was being cast to bool. This PR fixes that and we now check for both row and column layout.
We were doing:-
`std::unique_ptr<storage::DataTable> table(storage::TableFactory::GetDataTable(
INVALID_OID, INVALID_OID, table_schema, table_name,
tuples_per_tilegroup_count, own_schema, adapt_table, layout_type));`
Changed it to : 
`std::unique_ptr<storage::DataTable> table(storage::TableFactory::GetDataTable(
INVALID_OID, INVALID_OID, table_schema, table_name,
tuples_per_tilegroup_count, own_schema, adapt_table, is_catalog, layout_type));`
> Fix for #983

- src/catalog/catalog.cpp
- src/codegen/type/bigint_type.cpp
- src/codegen/type/decimal_type.cpp
- src/codegen/type/integer_type.cpp
- src/codegen/type/smallint_type.cpp
- src/codegen/type/tinyint_type.cpp
Just a few minor additions needed in the Floor function to make it correctly compatible across different numeric types. More or less following the additional suggestions provided in #898.
There was also some duplicate code related to the `ceiling` function - just removed the duplicate part.
Resolves #927
> Minor type related fixes/additions to Floor function

- script/installation/packages.sh
Oops, sorry about that but the fix eccc8b47468 I sent yesterday had a small typo introduced at the last minute. 😞  It didn't break the installation for Ubuntu 14.x, but didn't  work as intended for Ubuntu 15.x and 16.x. Now it works as expected for both versions as I just tested. Will keep my eyes really peeled next time. Again, sorry about that.
> Fix typo introduced by commit eccc8b47468

- src/common/internal_types.cpp
- src/include/parser/create_statement.h
- src/include/parser/drop_statement.h
- src/include/parser/parsenodes.h
- src/include/parser/postgresparser.h
- src/parser/parser_utils.cpp
- src/parser/postgresparser.cpp
- src/planner/drop_plan.cpp
- test/parser/parser_test.cpp
- test/parser/postgresparser_test.cpp
This PR adds support for a few types of queries in parser with corresponding tests
- With this PR the parser will be able to support queries like "CREATE INDEX ind ON t USING SKIPLIST (col);"
- With this PR the parser will be able to support queries like "CREATE SCHEMA schema_name;"
- With this PR the parser will be able to support queries like "CREATE VIEW view_name AS query;"
- Corresponding tests
Note: Postgres' default index type is "BTREE", while Peloton's is "BWTREE", as we do not currently support BTREE index type, the default index type is now set to BWTREE if no type is specified in the query.
> Parser support for a range of types of queries

- src/network/postgres_protocol_handler.cpp
- test/network/exception_test.cpp
This PR removes the `make_unique` introduced in #785 
@aaron-tian Could you check if it's good now? Thanks!
> Remove C++14 usage 

- src/concurrency/transaction_manager.cpp
- src/gc/gc_manager.cpp
- src/gc/transaction_level_gc_manager.cpp
- src/include/concurrency/transaction_context.h
- src/include/gc/gc_manager.h
- src/include/gc/transaction_level_gc_manager.h
- test/gc/garbage_collection_test.cpp
- test/gc/transaction_level_gc_manager_test.cpp
- test/include/common/harness.h
Fix for #954: This PR moves deallocation of TransactionContext to the GarbageCollector. This also gets rid of the garbage collection context and maintains a pointer to the TransactionContext in the queue till recycling.
> Fix for #954 : Refactor Garbage Collector

- script/git-hooks/pre-commit
- script/validators/source_validator.py
Since validator patterns are used repeatedly in a nested loop, it's better to compile them before for improved performance. Apart from these, at some places, source files were left open and not closed. I have fixed that security bug.
Lastly, I've tried to improve validator output, which till now gives redundant  and not much useful output when a format is violated.
Consider the old output:
```
12-23-2017 00:16:26 [<module>:222] INFO : Running source validator ...
12-23-2017 00:16:26 [<module>:223] INFO : Peloton root : /Users/binaryboy/Desktop/peloton
12-23-2017 00:16:26 [<module>:242] INFO : Scanning file : /Users/binaryboy/Desktop/peloton/src/main/peloton/peloton.cpp
12-23-2017 00:16:26 [check_common_patterns:112] INFO : Invalid pattern --  free\( -- found in : …
```
> Improved source validation

- script/coding_style.md
Modifying inlining rules:
- Don't use `inline` in member definitions - it's useless and dangerous.
- Don't have method definitions in class if they're too complex.
> Updating coding_style.md

- script/validators/source_validator.py
- test/optimizer/optimizer_test.cpp
* **Fix faulty commit a613847** (https://github.com/cmu-db/peloton/pull/991#issuecomment-356908046)
I am really sorry, thank you @pmenon for noticing that. 
* **Reset clang-format version in source validator to 3.6, to match the version in the formatter script**
I just noticed that clang-format of different version produces different output, so source validator and formatter script *must* use the same version. Which version can be discussed in #1015.
> [Fix] Fix faulty commit of #991 and reset clang-format version

- src/catalog/catalog.cpp
- src/codegen/codegen.cpp
- src/codegen/query_compiler.cpp
- src/codegen/type/bigint_type.cpp
- src/codegen/type/decimal_type.cpp
- src/codegen/type/integer_type.cpp
- src/codegen/type/smallint_type.cpp
- src/codegen/type/tinyint_type.cpp
- src/include/codegen/codegen.h
- test/function/functions_test.cpp
This PR enables codegen for all functions. Some functions are not supported, but will be implemented incrementally. This PR implements only `sqrt()`, the only extra function needed to pass the tests.
> Enable codegen for all functions

- src/catalog/catalog.cpp
- src/codegen/expression/comparison_translator.cpp
- src/codegen/proxy/string_functions_proxy.cpp
- src/codegen/type/varchar_type.cpp
- src/function/old_engine_string_functions.cpp
- src/function/string_functions.cpp
- src/include/codegen/proxy/string_functions_proxy.h
- src/include/function/old_engine_string_functions.h
- src/include/function/string_functions.h
- test/function/string_functions_test.cpp
This PR moves the string functions used by the interpreted engine into `OldEngineStringFunctions`. This is in preparation for 15-721. I also added the `Repeat` function to codegen to serve as an example.
> Move old string functions

- script/installation/packages.sh
partially back out abf963389e05fdbe99f52de801dccda230876619 to address running packages.sh multiple times.
> fix for #1067

- src/include/common/exception.h
Using `ExceptionTypeToString` instead of `ExpectionTypeToString`.
> Fix typo in exception.h

- src/common/container/cuckoo_map.cpp
- src/common/init.cpp
- src/common/statement_cache.cpp
- src/common/statement_cache_manager.cpp
- src/executor/drop_executor.cpp
- src/include/common/container/cuckoo_map.h
- src/include/common/statement.h
- src/include/common/statement_cache.h
- src/include/common/statement_cache_manager.h
- src/include/network/postgres_protocol_handler.h
- src/network/postgres_protocol_handler.cpp
- src/traffic_cop/traffic_cop.cpp
- test/common/cuckoo_map_test.cpp
- test/common/statement_cache_manager_test.cpp
- test/common/statement_cache_test.cpp
- test/executor/drop_test.cpp
- test/network/prepare_stmt_test.cpp
This is the plan cache that is used by Postgres protocol handler to support Prepare or extended protocol.
It would be updated when schema or index changes. The assumption is that the table schema or index rarely changes and the plan cache is not going to last for a very long time (drop when the connection tears down).
> Statement Cache

- test/common/statement_cache_manager_test.cpp
Someone posted a screenshot showing there would be compiled error in statement_cache_manager_test.cpp. 
I somehow encountered this before in statement_cache.cpp. I fixed that then but some errors remained unfound in the statement_cache_manager_test.cpp.
> statement_cache_manager_test fix for clang compile error

- cmake/ConfigGen.cmake
- cmake/Modules/CoverallsGenerateGcov.cmake
- src/CMakeLists.txt
- third_party/libpg_query/CMakeLists.txt
This PR changes the cmake build system to build libpg_query manually in the build folder using cmake instead of calling the provided Makefile. 
This works, but cmake spits out a warning I don't understand:
```
CMake Warning (dev) in src/CMakeLists.txt:
Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
Target "peloton" has an INTERFACE_LINK_LIBRARIES property which differs
from its LINK_INTERFACE_LIBRARIES_DEBUG properties.
INTERFACE_LINK_LIBRARIES:
peloton-proto;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost …
```
> [Cleanup] Change cmake to build libpg_query in build folder

- cmake/External/capnproto.cmake
This PR adds back some manual variable settings that are removed by #1083. Those are not set by capnproto automatically, and we need them to compile the proto files.
> Add back some variable settings for capnproto.

- src/brain/query_logger.cpp
- src/catalog/query_history_catalog.cpp
- src/include/brain/query_logger.h
- src/include/catalog/query_history_catalog.h
- test/brain/query_logger_test.cpp
Tonight, I rebased against master and ran into two tests failing because of memory leaks:
1. `query_logger_test`
2. `ssl_test`
As to how these changes made it into master without failing Travis is a separate issue. But, this PR fixes the first issue. 
`pg_query_fingerprint()` mallocs memory that must be freed by the caller through a companion call to `pg_query_free_fingerprint_result()`. This wasn't being done. I added a wrapper class that leverages RAII to make the appropriate call to safely free up allocated memory.
> Fix memory leak in query history logging

- src/include/threadpool/mono_queue_pool.h
- test/optimizer/cost_test.cpp
Minor fix to read the correct parameters for the worker and brain thread pool. This fixes the broken release build issue.
> Read the parameters of thread pool correctly from settings

- .travis.yml
- script/testing/jdbc/src/PelotonErrorTest.java
- script/testing/jdbc/src/PelotonTypeTest.java
I made a terrible mistake in #989, that allows travis builds to succeed, even if the tests and benchmarks fail. 
The section `after_success` ignores the exit code of the executed scripts. [1] I changed those scripts to be executed in the section `script`. 
Thanks to @pervazea for finding this and sorry to everyone for making this dump mistake :(
[1] https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build
> Fix travis build to check status of tests and benchmarks

- cmake/External/capnproto.cmake
It turned out that capnproto won't set any installation variables if we include it as an external project. However as #1083 described, we cannot manually hard-code the paths, nor can we directly remove those variable settings either.
This PR solves that issue by setting those variables with the default system installation directories provided by CMAKE.
> Fix the capnproto variable setting and linking issue.

- src/include/index/bwtree.h
- src/include/index/bwtree_index.h
- src/include/index/compact_ints_key.h
- src/include/index/generic_key.h
- src/include/index/index.h
- src/include/index/index_util.h
- src/include/index/tuple_key.h
- src/index/bwtree_index.cpp
- src/index/index_util.cpp
- test/index/testing_index_util.cpp
This is to help make it easier for the students to debug their project in the class. I am going to merge this unless anybody complains.
1. Added GetInfo methods for TupleKey and GenericKey.
2. Added IndexUtil::GetInfo(ItemPointer)
3. Added examples of debug output in BwTreeIndex::InsertEntry + DeleteEntry
https://www.youtube.com/watch?v=_QXRQRoO4IE
> Clean up of the index utility code

- src/codegen/codegen.cpp
- src/codegen/operator/order_by_translator.cpp
- src/codegen/type/bigint_type.cpp
- src/codegen/type/decimal_type.cpp
- src/codegen/type/type_system.cpp
- src/include/codegen/codegen.h
- test/sql/order_by_sql_test.cpp
This PR fixes a few issues related to sorting in codegen.
1. Fix sorting logic in the presence of NULLs.
2. Fix sorting of BigInt types, which was broken before due issuing a wrong sign-extension instruction.
3. Fix sorting of Decimal types, which was broken due to issuing wrong `sub` instruction.
4. Simplify the generated sort function.
5. Add sorting tests that include NULL data for both integers and strings.
> Fix order-by in codegen

- src/network/peloton_server.cpp
- src/network/postgres_protocol_handler.cpp
- src/network/protocol_handler.cpp
- src/network/service/network_address.cpp
The formatter script accidentally added duplicated headers in 4 files in 60f4f97fc4fde86926878d9e7f8f7e15a5e42c13, because an empty line was missing after the existing header. 
This PR simply removes one of them.
> Fix duplicated headers

- src/binder/bind_node_visitor.cpp
- src/include/common/exception.h
- src/optimizer/query_to_operator_transformer.cpp
- test/sql/insert_sql_test.cpp
Fixes #1055. I had to dig deep into `lldb` for this! I hope I've added the `throw` at the appropriate place. Using throw here also prevents the segfault from happening on, say `update` queries operating on a table that hasn't been created yet.
> Fix segfault for query on nonexistent tables

- script/git-hooks/pre-commit
This fixes the pre-commit hook bypass command, earlier it incorrectly attached `--no-verify` as a flag for the formatter script.
> Fix hook bypass command

- test/index/testing_index_util.cpp
Some of the index tests were not correctly creating unique-key indexes. UniqueKeyDeleteTest was also checking the wrong keys. This is for 15-721 project 2.
> Fix index tests

- src/include/catalog/catalog_cache.h
- src/include/parser/insert_statement.h
- src/include/parser/sql_statement.h
- src/include/parser/update_statement.h
- src/include/planner/plan_util.h
- src/include/util/set_util.h
- src/planner/plan_util.cpp
- test/planner/plan_util_test.cpp
- test/util/set_util_test.cpp
This is the first cut for #1097 
I can move the common functions like isDisjoint to some other more common utility class but first I want to get an idea if this is going in the right direction. :)
Also, I didn't create a new class as was described in the issue since there was already this PlanUtil in planner::
> Information about indexes affected by a given query

- .gitignore
- cmake/Dependencies.cmake
- cmake/ProtoBuf.cmake
- script/installation/packages.sh
- src/CMakeLists.txt
- src/brain/modelgen/LSTM_Model.py
- src/brain/modelgen/model_generator.py
- src/brain/modelgen/settings.json
- src/include/brain/tf_util.h
- test/brain/tensorflow_util_test.cpp
As part of this first step of Tensorflow integration, I'm adding the following:
1. Installation of Python(where necessary), Python3-Pip, Tensorflow binaries for C/Python. Also manual installation of Protobuf 3.4.0+
2. CMake changes for integrating tensorflow and automatically generating model files.
3. A simple test to check if tensorflow has imported correctly.
It first needs to build correctly on all platforms - We then incrementally add in our other developed modules for `peloton-brain`.
> Tensorflow Integration - Step 1

- src/binder/binder_context.cpp
- src/include/optimizer/cost_calculator.h
- src/include/optimizer/optimizer_metadata.h
- src/include/optimizer/stats/stats_storage.h
- src/include/optimizer/stats_calculator.h
- src/optimizer/cost_calculator.cpp
- src/optimizer/optimizer.cpp
- src/optimizer/optimizer_task.cpp
- src/optimizer/stats/stats_storage.cpp
- src/optimizer/stats_calculator.cpp
- test/optimizer/selectivity_test.cpp
- test/optimizer/stats_storage_test.cpp
As @poojanilangekar and @yingjunwu mentioned in previous emails, when visiting `ColumnStatsCatalog`, the stats storage use a `concurrency::TransactionContext*`  passed in as a parameter instead of creating a new one. This is a quick fix for that.
> Modify StatsStorage::GetTableStats() to take a txn as a parameter instead creating a new one

- script/installation/packages.sh
1. Fix so we do apt update for all Ubuntu variants
2. Add -e option to script, to exit on any failure, rather than
ignoring errors
Fixes courtesy of crd477
> Fix for #1209, packages.sh failures on Ubuntu Xenial

- src/include/optimizer/optimizer.h
- test/optimizer/optimizer_rule_test.cpp
This allows "make check" to work. 
A follow up issue has been created, to fix the optimizer tests to use accessor functions.
> Minimal fix for "make check", #1196

- .gitignore
- script/testing/junit/InsertPSTest.java
- script/testing/junit/InsertTPCCTest.java
- script/testing/junit/PLTestBase.java
- script/testing/junit/Readme.txt
Partially satisfying #1075.
This initial version focuses on prepared statement tests. A number of the tests fail due to issues documented in #1197. Those tests are currently disabled and will be enabled after the insert plan code is fixed.
> Initial Junit JDBC tests

- script/installation/packages.sh
Fix for Tensorflow crashes on Ubuntu Xenial.
Ubuntu Xenial needs Tensorflow 1.5+.
Ubuntu Trusty needs Tensorflow 1.4. With Tensorflow 1.5+, it then needs a lot of extra installations and upgraded packages.
> TF Xenial Fix

- src/codegen/type/decimal_type.cpp
Codegen returned a wrong type for the value created in `Decimal::CompareGtImpl` (Decimal instead of Boolean) which led to failing assertions when processing the value.
> Fix wrong return type in codegen Decimal::CompareGtImpl

- test/CMakeLists.txt
- test/leak_suppr.txt
Add a leak suppression file and pass it to make check. On other than sanitizer builds, it will be a no-op.
> Suppress Postgres parser mem leaks

- test/sql/insert_sql_test.cpp
I have checked all tests which expect exceptions. This was the only test where the transaction was not explicitly committed. We could abort these transactions but I noticed that most other tests try to commit the transactions which throw exceptions.
> Fix memory leak in the insert_sql_test [Partial fix for #1212]

- src/codegen/updater.cpp
- src/executor/update_executor.cpp
- src/include/codegen/updater.h
- src/include/common/internal_types.h
- src/include/common/item_pointer.h
- src/include/executor/update_executor.h
- src/include/storage/data_table.h
- test/executor/loader_test.cpp
- test/performance/insert_performance_test.cpp
- test/sql/update_sql_test.cpp
This PR fixes the Halloween Problem along with the sequential scan problem.
It builds on #1240 and checks for an entry in each WriteSet for each tuple (irrespective of whether or not it updates the Primary Key). 
I have tested this with varying tile_group_count. I have also tested the fix with and without codegen. It appears to have solved the Halloween problem for both the engines.
> Sequential Scan + Halloween Problem Fix 

- script/oltpbenchmark/benchmark.py
The previous file contained a small bug where it was ignoring all optional arguments, i.e. client time, scale factor, and transaction isolation settings. This is because argparse converts - to _ automatically.
This version also adds support for upload codes and upload URLs. Note that assigning to  root.find(...).text will fail if the sample config files do not contain the relevant XML keys. https://github.com/oltpbenchmark/oltpbench/pull/244
> Modify scripts/oltpbenchmark/benchmark.py

- src/catalog/manager.cpp
- src/common/container/cuckoo_map.cpp
- src/concurrency/timestamp_ordering_transaction_manager.cpp
- src/concurrency/transaction_context.cpp
- src/include/catalog/manager.h
- src/include/common/container/cuckoo_map.h
- src/include/common/internal_types.h
- src/include/concurrency/transaction_context.h
This PR fixes two of our performance bottlenecks.
1.  Modify the `tile_group_locator_` to use `CuckooMap` because it is faster for lookups. 
2. Modify the `ReadWriteSet` to use `tbb::concurrent_unordered_map` because it is faster for iterations.
> Performance Fixes

- src/common/internal_types.cpp
- src/concurrency/timestamp_ordering_transaction_manager.cpp
- src/concurrency/transaction_manager.cpp
- src/gc/transaction_level_gc_manager.cpp
- src/include/common/internal_types.h
- src/include/concurrency/transaction_context.h
- src/include/concurrency/transaction_manager.h
- test/common/internal_types_test.cpp
- test/concurrency/serializable_transaction_test.cpp
- test/include/concurrency/testing_transaction_util.h
this is to #1313 
Details:
1.remove IsolationLevelType::READ_ONLY
2.add a flag in transactioncontext 
3.re-implement 'IsReadOnly' function. This is safe because the function has not been call anywhere before this modification.
4.substitute every usage of 'READ_ONLY' with IsReadOnly function call
5.add a new parameter to BeginTransaction and provide a short cut 'BeginTransactionReadOnly'
6.one invocation of BeginTransaction(READ_ONLY) is changed to 'BeginTransactionReadOnly(IsolationLevelType::READ_COMMITTED);'
> fix #1313  Remove read only isolation level

- src/codegen/code_context.cpp
- src/codegen/function_builder.cpp
- src/codegen/lang/vectorized_loop.cpp
- src/codegen/operator/table_scan_translator.cpp
- src/codegen/util/sorter.cpp
- test/codegen/hash_table_test.cpp
Resolves the following introduced after merging PR #1304:
/peloton/src/codegen/function_builder.cpp:137:5: error: ‘~FunctionBuilder’ has a non-throwing exception specification but can still throw [-Werror,-Wexceptions]
/peloton/src/codegen/function_builder.cpp:135:18: note: destructor has a implicit non-throwing exception specification
/peloton/src/codegen/operator/table_scan_translator.cpp:219:37: error: lambda capture ‘table’ is not used [-Werror,-Wunused-lambda-capture]
/peloton/src/codegen/util/sorter.cpp:271:56: error: lambda capture ‘comp’ is not used [-Werror,-Wunused-lambda-capture]
/peloton/test/codegen/hash_table_test.cpp:100:17: error: variable ‘c1’ cannot be implicitly captured in a lambda with no capture-default specified
/peloton/test/codegen/hash_table_test.cpp:142:17: …
> Resolves Clang warnings and LLVM assertion failure on Mac

- src/codegen/transaction_runtime.cpp
- src/concurrency/timestamp_ordering_transaction_manager.cpp
- src/concurrency/transaction_context.cpp
- src/executor/hybrid_scan_executor.cpp
- src/executor/index_scan_executor.cpp
- src/executor/seq_scan_executor.cpp
- src/include/concurrency/timestamp_ordering_transaction_manager.h
- src/include/concurrency/transaction_manager.h
- src/storage/data_table.cpp
* add TileGroupHeader* as argument to ReadRecord to avoid lookup with GetTileGroup()
* rewrite access to RW set in TransactionContext::Record* functions to avoid duplicated lookups
> Performance Fixes: pass TileGroupHeader*, avoid RW set lookups

- test/codegen/csv_scan_translator_test.cpp
Resolves the following warning introduced by #1371 on Clang 9.1:
../git/peloton/test/codegen/csv_scan_translator_test.cpp:39:30: error: lambda capture 'quote' is not required to be captured for this use [-Werror,-Wunused-lambda-capture]
const auto quote_string = [quote](std::string s) {
I couldn't reproduce the warning on GCC 7.3, which makes me wonder if it's spurious on Clang's part. However, I ran make check with this proposed change under Clang 9.1 and GCC 7.3 and everything looked good. Hopefully it's the same story on Jenkins and Travis.
> Fix warning for unused lambda capture on Clang 9.1

- src/codegen/util/hash_table.cpp
- test/codegen/hash_table_test.cpp
Avoids a call to `NextPowerOf2` with zero when the hash table doesn't contain any elements in the function `HashTable::BuildLazy`. Occurred when running TPC-H Q3 in Peloton.
> Fix HashTable::BuildLazy if it contains zero emelemts

- src/common/container/lock_free_array.cpp
- src/concurrency/timestamp_ordering_transaction_manager.cpp
- src/concurrency/transaction_context.cpp
- src/include/common/container/lock_free_array.h
- src/include/concurrency/transaction_context.h
- src/storage/data_table.cpp
- test/common/lock_free_array_test.cpp
**LockFreeArray:**
- Changed functions that unconditionally returned true to be void.
- Rewrote FindValid to no longer be O(n) lookups. This is used in DataTable:GetTileGroup() and should be fast.
- Added Doxygen comments.
- Added more tests.
**TimestampOrderingTransactionManger:**
- Keep track of last accessed tile_group_id and if it's the same avoid going to the StorageManager’s CuckooHashMap for the TileGroup.
**TransactionContext:**
- Simplified conditionals to what should be equivalent logic. Reduced lookups for Release mode, increased lookups in Debug mode (by moving lookups that only served for PELOTON_ASSERTs into individual lookups inside the ASSERTs)
- Removed the iterator hints since Intel docs show they're not used:
https://software.intel.com/en-us/node/506175
- Removed …
> RWSet performance fixes, LockFreeArray performance fixes and tests

- src/concurrency/timestamp_ordering_transaction_manager.cpp
- src/gc/transaction_level_gc_manager.cpp
- src/include/concurrency/timestamp_ordering_transaction_manager.h
- src/include/storage/tile_group_header.h
- src/storage/tile_group_header.cpp
This is just a refactor of the TileGroupHeader to make it a bit more modifiable/maintainable. I got rid of the char array that used hardcoded pointer arithmetic to access tuple "fields". Made each tuple header slot be a struct of fields, and made an array of those to represent all of the tuples in the TileGroup. These are all managed by smart pointers now.
There's also no "reserved" area in a tuple header anymore, since it was full anyway for other purposes (spin latch and last reader) so I broke those out into proper fields.
> TileGroupHeader refactor

- src/concurrency/timestamp_ordering_transaction_manager.cpp
- src/concurrency/transaction_context.cpp
- src/include/concurrency/transaction_context.h
Addresses point 2 in #1420. There's no reason to add READs to the RWSet in MVTO.
> Skip adding READs to the RWSet

- src/concurrency/timestamp_ordering_transaction_manager.cpp
- src/include/storage/tile_group_header.h
- src/storage/tile_group_header.cpp
This addresses a good comment @pmenon brought up after merging #1423. I misinterpreted the old pointer casting and layout of the old headers, and made the SpinLatch field a pointer to a separately allocated SpinLatch. Instead, it should have been inlined in the header.
This addresses a potential performance issue in the future of having to chase another pointer. Right now we see no difference in TPC-C and YCSB, but we should fix it now.
> Inline tuple SpinLatch after TileGroupHeader refactor

- src/concurrency/timestamp_ordering_transaction_manager.cpp
Addresses points 5 and 6 of #1420. MVTO should set the Last Reader timestamp to be the version creator's timestamp.[1] This was previously not done, and could trigger an assertion failure in Debug mode.
[1]A. Silberschatz, H. Korth and S. Sudarshan, _Database System Concepts_, 6th ed. New York: McGraw Hill, 2011, p. 690.
> Set LastReaderCommitId on new versions

- test/brain/tensorflow_test.cpp
Workaround for #1448. This change should be reverted once the tensorflow package is updated with Python 3.7 compatibility.
> Disable TensorFlow tests to allow Travis macOS builds to succeed.

- src/optimizer/group_expression.cpp
- src/optimizer/memo.cpp
- test/optimizer/optimizer_rule_test.cpp
- test/sql/testing_sql_util.cpp
Fixes false positive in rule checking (#1234). The error was being caused by incorrect use of `bitmap.set` function. I also added a plan printing helper function. Lastly, I improved our group expression equality function. While it's not a complete fix to #1354, it helps. 
@apavlo For some reason PR #1245 never got checked in (it says merged but the changes aren't in the code), so I'm submitting this one. We never merged in my PR for the class (#1344), however, that also included the bug fixes we found during the semester. I'm gonna add those in separate PRs like this one.
> Fix for optimizer rule bug
